### ISSUE TITLE
PING probe false positive in podman environment 

### ISSUE THREAD

**Issue by hncrio** [cloudprober/cloudprober#100]
**Describe the bug**
Host is not up but the success rate is %100 

**Cloudprober Version**
0.11.4

**To Reproduce**
I am trying to run the container on podman which was installed via brew. 
 
1. Crete Dockerfile and cloudprobe.cfg 
$ cat Dockerfile
FROM docker.io/cloudprober/cloudprober
COPY cloudprober.cfg /etc/cloudprober.cfg

$cat cloudprober.cfg
probe {
  name: "cn01"
  type: PING
  targets {
    host_names: "172.16.10.108"
  }
  interval_msec: 5000  # 5s
  timeout_msec: 1000   # 1s
}
2. podman build -t hncr.io/cloudprober .

4. podman run --name observer --network host hncr.io/cloudprober:latest

5. cloudprober 1646355191063709290 1646357755 labels=ptype=ping,probe=cn01,dst=172.16.10.108 total=1024 success=1024 latency=1765228.603 validation_failure=map:validator,data-integrity:0

6. ping 172.16.10.108
PING 172.16.10.108 (172.16.10.108): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
**Additional context**

❯ podman info
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.0-2.fc35.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: '
  cpus: 1
  distribution:
    distribution: fedora
    variant: coreos
    version: "35"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.15.18-200.fc35.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 1034878976
  memTotal: 2061381632
  ociRuntime:
    name: crun
    package: crun-1.4.2-1.fc35.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.4.2
      commit: f6fbc8f840df1a414f31a60953ae514fa497c748
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc35.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 5h 54m 19.4s (Approximately 0.21 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /var/home/core/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/core/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 5
  runRoot: /run/user/1000/containers
  volumePath: /var/home/core/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.4
  Built: 1638999907
  BuiltTime: Wed Dec  8 21:45:07 2021
  GitCommit: ""
  GoVersion: go1.16.8
  OsArch: linux/amd64
  Version: 3.4.4

➜ podman inspect hncr.io/cloudprober:latest
[
    {
        "Id": "fe71b1a63c8e16cdfe0780377a493cf14197ca8b3272be514782f60b1bbaa92d",
        "Digest": "sha256:0ddfb4018e10acf4ab84a59a9cf630ec4f79ba31ff505562237cc54a220c46d6",
        "RepoTags": [
            "hncr.io/cloudprober:latest"
        ],
        "RepoDigests": [
            "hncr.io/cloudprober@sha256:0ddfb4018e10acf4ab84a59a9cf630ec4f79ba31ff505562237cc54a220c46d6"
        ],
        "Parent": "e93c1a15f4fe0cabdece87fbad954ad7a382ccedeb24334e118e3e7dbe4b5332",
        "Comment": "",
        "Created": "2022-03-04T00:53:05.30462115Z",
        "Config": {
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Entrypoint": [
                "/cloudprober",
                "--logtostderr"
            ],
            "Labels": {
                "com.microscaling.license": "Apache-2.0",
                "io.buildah.version": "1.23.1",
                "org.label-schema.build-date": "2022-02-03T17:44:39Z",
                "org.label-schema.name": "Cloudprober",
                "org.label-schema.vcs-ref": "87c4d42",
                "org.label-schema.vcs-url": "https://github.com/cloudprober/cloudprober",
                "org.label-schema.version": "v0.11.4"
            }
        },
        "Version": "",
        "Author": "",
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 37597201,
        "VirtualSize": 37597201,
        "GraphDriver": {
            "Name": "overlay",
            "Data": {
                "LowerDir": "/var/home/core/.local/share/containers/storage/overlay/263bbc5a92eefaa97313514e6b529bb0ea2ce41a77a7a072032bcc048f64eb13/diff:/var/home/core/.local/share/containers/storage/overlay/bd8a0b959097fa3cd5d3f32861a0a64eaa2c70203ba997c0f1b9d78e329e59a9/diff:/var/home/core/.local/share/containers/storage/overlay/01fd6df81c8ec7dd24bbbd72342671f41813f992999a3471b9d9cbc44ad88374/diff",
                "UpperDir": "/var/home/core/.local/share/containers/storage/overlay/b0e1fe57c82b6e6e751edf401e9022a5dbbf1dd547a009e2c7d6befa2eee1e1f/diff",
                "WorkDir": "/var/home/core/.local/share/containers/storage/overlay/b0e1fe57c82b6e6e751edf401e9022a5dbbf1dd547a009e2c7d6befa2eee1e1f/work"
            }
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:01fd6df81c8ec7dd24bbbd72342671f41813f992999a3471b9d9cbc44ad88374",
                "sha256:503aacf61ed5d42a83f53b799a8a9db04d97ec8bcaaf0e4b6fd444996e871e50",
                "sha256:6dcfbd8fd01b2caee7d30f68704959d00919395b1e6838cb17ab9c8ced22f798",
                "sha256:6a0241365673036d387cc582cff0c836f3a11c7cc00b197a4af460d48d24c6af"
            ]
        },
        "Labels": {
            "com.microscaling.license": "Apache-2.0",
            "io.buildah.version": "1.23.1",
            "org.label-schema.build-date": "2022-02-03T17:44:39Z",
            "org.label-schema.name": "Cloudprober",
            "org.label-schema.vcs-ref": "87c4d42",
            "org.label-schema.vcs-url": "https://github.com/cloudprober/cloudprober",
            "org.label-schema.version": "v0.11.4"
        },
        "Annotations": {
            "org.opencontainers.image.base.digest": "sha256:d3121c10aeca683132fb61a06b533f71629fdeb26503671e89531978453ff9ec",
            "org.opencontainers.image.base.name": "docker.io/cloudprober/cloudprober:latest"
        },
        "ManifestType": "application/vnd.oci.image.manifest.v1+json",
        "User": "",
        "History": [
            {
                "created": "2021-12-30T19:19:40.833034683Z",
                "created_by": "/bin/sh -c #(nop) ADD file:6db446a57cbd2b7f4cfde1f280177b458390ed5a6d1b54c6169522bc2c4d838e in / "
            },
            {
                "created": "2021-12-30T19:19:41.006954958Z",
                "created_by": "/bin/sh -c #(nop)  CMD [\"sh\"]",
                "empty_layer": true
            },
            {
                "created": "2022-02-03T17:44:51.485420889Z",
                "created_by": "COPY ca-certificates.crt /etc/ssl/certs/ca-certificates.crt # buildkit",
                "comment": "buildkit.dockerfile.v0"
            },
            {
                "created": "2022-02-03T17:44:54.125768865Z",
                "created_by": "COPY /stage-0-workdir/cloudprober / # buildkit",
                "comment": "buildkit.dockerfile.v0"
            },
            {
                "created": "2022-02-03T17:44:54.125768865Z",
                "created_by": "ARG BUILD_DATE",
                "comment": "buildkit.dockerfile.v0",
                "empty_layer": true
            },
            {
                "created": "2022-02-03T17:44:54.125768865Z",
                "created_by": "ARG VERSION",
                "comment": "buildkit.dockerfile.v0",
                "empty_layer": true
            },
            {
                "created": "2022-02-03T17:44:54.125768865Z",
                "created_by": "ARG VCS_REF",
                "comment": "buildkit.dockerfile.v0",
                "empty_layer": true
            },
            {
                "created": "2022-02-03T17:44:54.125768865Z",
                "created_by": "LABEL org.label-schema.build-date=2022-02-03T17:44:39Z org.label-schema.name=Cloudprober org.label-schema.vcs-url=https://github.com/cloudprober/cloudprober org.label-schema.vcs-ref=87c4d42 org.label-schema.version=v0.11.4 com.microscaling.license=Apache-2.0",
                "comment": "buildkit.dockerfile.v0",
                "empty_layer": true
            },
            {
                "created": "2022-02-03T17:44:54.125768865Z",
                "created_by": "ENTRYPOINT [\"/cloudprober\" \"--logtostderr\"]",
                "comment": "buildkit.dockerfile.v0",
                "empty_layer": true
            },
            {
                "created": "2022-03-04T00:53:05.305970995Z",
                "created_by": "/bin/sh -c #(nop) COPY file:e5d838cb326e5be33db8cb94bd29366f592a4f928a93fc1d878bfe288d662cbf in /etc/cloudprober.cfg ",
                "comment": "FROM docker.io/cloudprober/cloudprober:latest"
            }
        ],
        "NamesHistory": [
            "hncr.io/cloudprober:latest"
        ]
    }
]

**Comment by manugarg** [comment]
@hncrio Thanks for reporting the bug. I'm not sure what might be going on here.

Have you tried running cloudprober outside of podman, similar to how you ran ping? You can download the binary from here: https://github.com/cloudprober/cloudprober/releases/download/v0.11.4/cloudprober-v0.11.4-linux-x86_64.zip

**Comment by hncrio** [comment]
@manugarg  I am on MacOS 11.6.1 
Binary works as expected. 

#TYPE success counter
success{ptype="ping",probe="cn01",dst="172.16.10.108"} 0 1646388879829
#TYPE latency counter
latency{ptype="ping",probe="cn01",dst="172.16.10.108"} 0.000 1646388879829

[My current setup is described here in detail](https://www.redhat.com/sysadmin/podman-mac-machine-architecture)

**Comment by manugarg** [comment]
I see. It seems like a podman environment issue then.

Looks like one of the ways to verify this issue will be to do this:

```
podman run -it --rm
...
# dnf -y install iputils
....
# ping 172.16.10.108
```

**Comment by manugarg** [comment]
@hncrio I was wondering if you wanted to continue pursuing it, or we close it for now.

My guess is that podman networking has a role to play here. The best way to proceed will be to compare "ping" and "cloudprober" in the podman environment.

Let me know.

**Comment by hncrio** [comment]
Sorry for the delay.  I am using the container image you released. 
Ping binary is part of busybox I guess. 

`$podman run -it --rm  --network host hncr.io/cloudprober:latest`

`$podman ps`
`CONTAINER ID  IMAGE                             COMMAND               CREATED     STATUS         PORTS                   NAMES`
`9dad99293770  hncr.io/cloudprober:latest                              2 days ago  Up 2 days ago                          laughing_albattani`


`$podman exec -it laughing_albattani /bin/sh`
```
# ping 172.16.10.108
PING 172.16.10.108 (172.16.10.108): 56 data bytes
ping: permission denied (are you root?
# cat /etc/cloudprober.cfg
probe {
  name: "cn01"
  type: PING
  targets {
    host_names: "172.16.10.108"
  }
  interval_msec: 5000  # 5s
  timeout_msec: 1000   # 1s
}
```
I will dig further to make ping work inside that image.

**Comment by manugarg** [comment]
> I see. It seems like a podman environment issue then.
> 
> Looks like one of the ways to verify this issue will be to do this:
> 
> ```
> podman run -it --rm
> ...
> # dnf -y install iputils
> ....
> # ping 172.16.10.108
> ```

If you install ping like this, that "ping" should work. It seems iputils' ping supports non-privileged ICMP.

**Comment by hncrio** [comment]
Thanks, I confirm that this is an environment issue. 
Spinning up an official fedora image with iputils installed, I get ICMP reply for all the IP addresses which does not exist in the network. 
Sorry for the noise.

**Comment by manugarg** [comment]
> Thanks, I confirm that this is an environment issue.
> Spinning up an official fedora image with iputils installed, I get ICMP reply for all the IP addresses which does not exist in the network.
> Sorry for the noise.

No problem. I got to learn a bit about podman because of this :). Cheers!
