### ISSUE TITLE
Document debugging tips

### ISSUE THREAD

**Issue by jtse** [cloudprober/cloudprober#101]
I think it would be useful to have a page on debugging tips. For example:

*  Use `--debug_log` for more verbose logging which will include the probe response.
*  Use `--disable_cloud_logging` to log to console rather than redirect to Stackdriver if you're on GCE.

I'm not sure of the best place to put these tips.

**Comment by vancouverwill** [comment]
strongly agree about this, it is quite hard to work out what went wrong at times with just just  a success or faillure output

**Comment by manugarg** [comment]
I've started a wiki page here: https://github.com/cloudprober/cloudprober/wiki/Debugging-Tips

>> Use --disable_cloud_logging to log to console rather than redirect to Stackdriver if you're on GCE.

All logs now go to stderr, regardless. On GCE they also go to Stackdriver.
