### ISSUE TITLE
Support for discovering GCP global forwarding rules targets

### ISSUE THREAD

**Issue by muntakimsadik** [cloudprober/cloudprober#106]
Currently cloudprober can only discover forwarding rules that are tied to a region (https://github.com/cloudprober/cloudprober/blob/master/targets/gce/proto/config.proto#L53-L63). I need to probe targets that are configured as global forwarding rules. For that cloudprober needs the ability to discover global forwarding rules.

**Comment by muntakimsadik** [comment]
I tried to put together a pull request to implement this (https://github.com/cloudprober/cloudprober/pull/107). Please let me know if that aligns with how cloudprober is supposed to work.

**Comment by manugarg** [comment]
@muntakimsadik, sorry for the delay, and thanks for the PR. Merged it.
