### ISSUE TITLE
file_targets re_eval option is not working

### ISSUE THREAD

**Issue by momoXD007** [cloudprober/cloudprober#136]
**Describe the bug**
When configuring a file-target with the re_eval_sec = 30 I expect that the file-target is reevaluated every 30 seconds and if it changes new targets will be probed or targets that do not exist anymore are not probed anymore.
However, none of that happens. The cloudprober just continues to probe those targets configured at startup and does not care about changes at all. 
Upon container-restart new targets/missing targets are correctly parsed.
In the setup I run I see this for bundled probers like the HTTP-prober the same as for my custom-developed tools bundled inside the same container.

**Cloudprober Version**
binary extracted from https://hub.docker.com/r/cloudprober/cloudprober on  10 May 2022  and copied into an ubuntu 20.04 based image running golang 17.1

**To Reproduce**
Start a cloudprober container with the following config:

```
probe {
  name: "scs_probe"
  type: HTTP
  http_probe {
    protocol: HTTPS
    relative_url: "/alive"
    resolve_first: true
    tls_config {
      disable_cert_validation: true
    }
  }
  targets {
    file_targets {
      file_path: "/etc/scs.json"
      re_eval_sec: 30
    }
  }
  interval_msec: 5000
  timeout_msec:  16000
}

```

content of scs.json
```
{
    "resource": [
      {
        "name": "8.8.8.8",
        "ip": "8.8.8.8",
        "port": 443,
        "labels": {
          "host": "my-example.cloud"
        }
      },
      {
        "name": "1.1.1.1",
        "ip": "1.1.1.1",
        "port": 443,
        "labels": {
          "host": "other-stuff.de"
        }
      }
    ]
  }
```

2. change content of scs.json eg.: add a new endpoint
3. wait at least 30 seconds
4. see if the changes in scs.json  are reflected in the output. Depending on the changes performed we expect either new or stopped metrics in searches like this:  latency{probe="scs_probe"}.  AS an example if we started with the above scs.json and just added a new target 2.2.2.2 we expect that after roughly 30 seconds metrics for dst="2.2.2.2" appear. 
--> However, in my testing the metrics for this new target will not appear even after days of waiting, they will however immediately appear once the cloud prober-container is restarted.

**Additional context**
It is possible something in my build process for my custom-cloudprober leads to this problem, but I feel like it is unlikely as this issue is present bundled probes and not just with my custom-probes. H

**Comment by manugarg** [comment]
This is indeed a bug[1]. We are not passing along re_eval_sec when Much thanks for reporting this @momoXD007.

I'll submit a fix soon, but in the meantime there is a workaround for this -- you can explicitly use rds_server and rds_targets (that's what happens behind the scene anyway):

```
Use this for targets:

targets {
  rds_targets {
    resource_path: "file://"
  }
}
```

and add this rds_server:
```
rds_server {
  provider {
    file_config {
      file_path: "..."
      re_eval_sec: 30
    }
  }
}
```

[1] Bug is this: We are not passing re_eval_sec when we create RDS file provider. https://github.com/cloudprober/cloudprober/blob/5bec0db1ac908e69bff0fbca3182415c4e267d64/targets/file/file.go#L35

**Comment by manugarg** [comment]
Above commit should fix it.  It will go out in the next release:
v0.11.8: https://github.com/cloudprober/cloudprober/milestone/5
