### ISSUE TITLE
[HTTP Probe] Probe uses HTTP/1.1 instead of HTTP/2.0 when connecting to api.push.apple.com

### ISSUE THREAD

**Issue by archaron** [cloudprober/cloudprober#139]
**Describe the bug**
I'm trying to probe apple's push API reachability. Target seems to support HTTP/2.0 only. 
Docs says that HTTP/2 is enabled by default, but probe have no luck with request.
```
 http.go:298] [cloudprober.apple_push] Target:api.push.apple.com, URL:https://api.push.apple.com, http.doHTTPRequest: Get "https://api.push.apple.com": net/http: HTTP/1.x transport connection broken: malformed HTTP status code "HTTP/1.x"
```
As I can see, there is no way to enforce HTTP/2 for specific target. Wish there be an option to do so, like 'enforce_http2'.
We need to set  http.Transport field ForceAttemptHTTP2 to true.

**Cloudprober Version**
v0.11.7

**To Reproduce**
```
probe {
    name: "apple_push"
    type: HTTP
    targets {
      host_names: "api.push.apple.com"
    }

    http_probe {
      protocol: HTTPS
    }

    ip_version: IPV4
  }

```

**Additional context**
Some test code to reproduce the problem. Try to uncomment ForceAttemptHTTP2.

```golang
package main

import (
	"fmt"
	"net"
	"net/http"
	"time"
)

func main() {

	dialer := &net.Dialer{
		Timeout:   5 * time.Second,
		KeepAlive: 30 * time.Second, // TCP keep-alive
	}

	transport := &http.Transport{
		DialContext: dialer.DialContext,
		//ForceAttemptHTTP2: true,
	}

	client := &http.Client{
		Transport: transport.Clone(),
	}

	resp, err := client.Get("https://api.push.apple.com/")
	if err != nil {
		panic(err)
	}
	fmt.Println(resp.Status)
}
```

**Comment by manugarg** [comment]
I see that we don't use DefaultTransport which automatically enables ForceAttemptHTTP2. I'll look into it.

**Comment by manugarg** [comment]
Last commit should fix this. It will go out in the next release: [v0.11.8](https://github.com/cloudprober/cloudprober/milestone/5).
