### ISSUE TITLE
https probe with resolve_first failing due to certificate mismatch

### ISSUE THREAD

**Issue by tarrychk** [cloudprober/cloudprober#158]
**Describe the bug**
Using http_probe in HTTPS mode with resolve_first=true option causes certificate mismatch errors because the actual request is done with the resolved ip address *without* setting TLS server_name to the original host name. This can be mitigated by manually configuring tlsconfig.server_name in http_probe, but this falls short when I have multiple targets with different target hosts.

**Cloudprober Version**
v0.11.8

**To Reproduce**
1. Minimal configuration (I replaced target fqdn and ip address with dummy values):
   ```
   probe {
     name: "reproducer"
     type: HTTP
     targets {
       file_targets {
         file_path: "resources.json"
       }
     }
     http_probe {
       protocol: HTTPS
       resolve_first: true
       #tls_config {
       #  server_name: "www.example.org"
       #}
     }
   }
   ```
   resources.json:
   ```
   {
     "resources": [
       {
         "name": "www.example.org",
         "ip": "127.0.0.1",
         "port": 443,
         "labels": {
           "fqdn": "www.example.org"
         }
       }
     ]
   }
   ```
1. Run cloudprober:
    W0608 15:04:12.985724       1 http.go:321] [cloudprober.reproducer] Target:www.example.org, URL:https://127.0.0.1:443, http.doHTTPRequest: Get "https://127.0.0.1:443": x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs

**Additional context**
Explicitly configuring tlsconfig server_name resolves the issue but requires to write a dedicated probe for every target. Unfortunately substitutions do not work here. Being able to use `server_name: "@target.label.fqdn@"` would have been nice but the value gets passed verbatim.
Setting `resolve_first: true` is important for my use case because I want to override the target host with the ip address I configured in the targets "ip" field.

**Comment by manugarg** [comment]
Thanks a lot for reporting this issue, @tarrychk. Just to make sure I understand it correctly this issue is not new in v0.11.8, right? It doesn't seem like it should be.

**Comment by manugarg** [comment]
To record my findings so far, solving this is going to be slightly tricky. There are two possible solutions, none very straightforward:

1. Override transport's `DialTLSContext` function to copy TLSConfig and override ServerName before starting TLS connection. To be able to do this though, DialTLSContext itself should know the target name, but it gets only the _network_ and _addr_  in its arguments. There are two ways to solve this -- create per target http.Transport, or keep a probe-wide addr-to-target-name/fqdn map and update it from time to time.

2. Override transport's DialContext function to call target's resolver function (if resolving first) before establishing the connection. This will change a lot of things, mostly for the better, but we'll have to be very careful. Another problem with this solution is that probe logs won't contain the IP information for request failures.

**Comment by manugarg** [comment]
#159 has one possible solution using per target http.Transport.

**Comment by tarrychk** [comment]
I tested #159 and it fixes the issue for me.

**Comment by manugarg** [comment]
Thanks a lot for verifying @tarrychk. I've merged the PR.

**Comment by manugarg** [comment]
Marking this closed. This will go out in the next release: v0.11.9. Next release date is not planned yet, please let me know if you cannot use the "master" tag or the latest binaries, and would like the release to come out sooner.
