### ISSUE TITLE
Allow debugging configuration templates, and playbook

### ISSUE THREAD

**Issue by cool-RR** [cloudprober/cloudprober#16]
This issue started when the repository was under Google, see full context here: https://github.com/google/cloudprober/issues/651

This is a need I've had a few weeks ago, and now my teammate @maayanch has the same need as well.

We have a Cloudprober configuration template that may have different variables, different regular expressions that we match, etc. Sometimes it doesn't match the machines we think it should be matching. We want to understand how to debug it so we wouldn't have to do trial-and-error in the dark. We want visibility into all the variables. We want to be able to print stuff and see the output.

Are these things currently possible? If so, there should be a playbook or a documentation page that shows the different ways to debug Cloudprober configuration templates.

**Comment by manugarg** [comment]
You can see running config now from the status page. There are multiple handlers: /config, /config-parsed, /config-running.
