### ISSUE TITLE
External probe: Defunct processes may remain behind after probe timeout

### ISSUE THREAD

**Issue by tksm** [cloudprober/cloudprober#165]
**Describe the bug**

When we use an external probe that forks a child process, the defunct child process may remain behind after probe timeout.

Since the cloudprober is PID 1 in a container environment, I think the cloudprober should reap defunct processes like `init` does. Alternatively, we can put another entrypoint that can reap defunct processes such as Busybox and [Tini](https://github.com/krallin/tini).

```
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         137  4.0  0.0   5892  2996 ?        Rs   03:00   0:00 ps auxfw
root           1  0.3  0.7 740840 30028 ?        Ssl  02:59   0:00 /cloudprober --logtostderr -config_file /opt/cloudprober.cfg
root          14  0.0  0.0      0     0 ?        Z    02:59   0:00 [sleep] <defunct>
root          40  0.0  0.0      0     0 ?        Z    02:59   0:00 [sleep] <defunct>
root          74  0.0  0.0      0     0 ?        Z    03:00   0:00 [sleep] <defunct>
root         108  0.0  0.0      0     0 ?        Z    03:00   0:00 [sleep] <defunct>
root         135  0.0  0.0   1316     4 ?        S    03:00   0:00 /bin/sh /opt/probe.sh
root         136  0.0  0.0   1308     4 ?        S    03:00   0:00  \_ /bin/sleep 3
```

**Cloudprober Version**

v0.11.8

**To Reproduce**

1. Place the config and the probe script

probe.sh

```sh
#!/bin/sh
/bin/sleep 3
echo done
```

cloudprober.cfg

```
probe {
  name: "dummy"
  type: EXTERNAL
  interval_msec: 5000
  timeout_msec: 1000
  targets { dummy_targets {} }
  external_probe {
    mode: ONCE
    command: "/opt/probe.sh"
  }
}
```

2. Run the cloudprober in Docker

```
docker run --name cp-sleep --rm -v $PWD:/opt/ cloudprober/cloudprober:v0.11.8 -config_file /opt/cloudprober.cfg
```

3. Defunct sleep processes remain behind

```
docker run --pid container:cp-sleep ubuntu:20.04 ps auxfw
```

```
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         137  4.0  0.0   5892  2996 ?        Rs   03:00   0:00 ps auxfw
root           1  0.3  0.7 740840 30028 ?        Ssl  02:59   0:00 /cloudprober --logtostderr -config_file /opt/cloudprober.cfg
root          14  0.0  0.0      0     0 ?        Z    02:59   0:00 [sleep] <defunct>
root          40  0.0  0.0      0     0 ?        Z    02:59   0:00 [sleep] <defunct>
root          74  0.0  0.0      0     0 ?        Z    03:00   0:00 [sleep] <defunct>
root         108  0.0  0.0      0     0 ?        Z    03:00   0:00 [sleep] <defunct>
root         135  0.0  0.0   1316     4 ?        S    03:00   0:00 /bin/sh /opt/probe.sh
root         136  0.0  0.0   1308     4 ?        S    03:00   0:00  \_ /bin/sleep 3
```

**Comment by tksm** [comment]
In Kubernetes, enabling [`shareProcessNamespace`](https://kubernetes.io/docs/tasks/configure-pod-container/share-process-namespace/) also solves this issue because the pause container, [which can reap defunct processes](https://github.com/kubernetes/kubernetes/blame/3beb8dc5967801bcaed4541b307dbcdbd86fda3d/build/pause/linux/pause.c#L37-L40), takes PID 1.

**Comment by manugarg** [comment]
Thanks a lot @tksm for reporting this issue, a way to reproduce this, and workarounds.

Docker also has a flag that takes care of this: https://docs.docker.com/engine/reference/run/#specify-an-init-process

I'll look into implementing this functionality in Cloudprober itself or change the Dockerfile.

**Comment by manugarg** [comment]
Looked at this a bit more. The real issue here is that Cloudprober kills the external probe process when probe times out, but it does not kill processes started by the probe process, for example in the example above, it will kill the shell process but it will not kill the `sleep` process started by the shell process.

References:
https://cs.opensource.google/go/go/+/refs/tags/go1.18.3:src/os/exec/exec.go;l=454
https://cs.opensource.google/go/go/+/refs/tags/go1.18.3:src/os/exec.go;l=122

However, I think it still makes sense to have Cloudprober handle SIGCHLD. It will only be relevant when Cloudprober is running as the `init` process.

**Comment by manugarg** [comment]
PR https://github.com/cloudprober/cloudprober/pull/166 has a fix for this. I verified that it doesn't create any defunct processes any more.

**Comment by manugarg** [comment]
https://github.com/cloudprober/cloudprober/pull/167 has a possible solution using process groups.

**Comment by manugarg** [comment]
Committed the change. You should be able to test it out using ":master" docker image.

**Comment by tksm** [comment]
Thank you for implementing this feature!
I confirmed that defunct processes are no longer left behind with the `cloudprober/cloudprober:master` image. 👍
