### ISSUE TITLE
Document templating language

### ISSUE THREAD

**Issue by cool-RR** [cloudprober/cloudprober#17]
This issue started when the repository was under Google, see full context here: google/cloudprober#637

Cloudprober has some kind of templating language in its configuration. I couldn't figure out what language is that. Didn't find it on the readme or in the docs. It needs to be document because people need to know exactly what they can do with this language, and how.

Another thing that needs to be documented here: Which variables are automatically available to us. I know that I can use `.region`, but do I automatically get `.zone`? I have to try to find out. Would be nice if I just had a list of all the variables that are available to me.

**Comment by manugarg** [comment]
Cloudprober's config language is Go template based. Beyond that it's documented at:
https://pkg.go.dev/github.com/cloudprober/cloudprober@v0.13.6/config

I guess still needs a few updates about sprig functions support.

Most of the config fields are documented at:
https://cloudprober.org/docs/config/overview/
