### ISSUE TITLE
more information about error "logging client: rpc error: code = PermissionDenied desc = The caller does not have permission"

### ISSUE THREAD

**Issue by shi-ron** [cloudprober/cloudprober#174]
Hi,
I'm running the cloudprober in GKE and the pod console continuously returns error
```
logging client: rpc error: code = PermissionDenied desc = The caller does not have permission
```
The service account used have already assigned to the IAM `roles/monitoring.editor` and `roles/monitoring.metricWriter`.
It shall be helpful to give more information about the permission error.

**Comment by manugarg** [comment]
@shi-ron Can you try disabling the cloud logging completely, using either the `disable_cloud_logging` flag or by setting the environment variable: CLOUDPROBER_DISABLE_CLOUD_LOGGING to "YES".

I think logging permission is separate from the monitoring permissions.

**Comment by shi-ron** [comment]
Disabling logging works. Thanks.
