### ISSUE TITLE
errors when running ping tests on raspberry pi3. timestamp control message data size (8) is less than timestamp size (16 bytes)

### ISSUE THREAD

**Issue by morhold** [cloudprober/cloudprober#175]
**Describe the bug**
errors when running ping tests on raspberry pi3.
timestamp control message data size (8) is less than timestamp size (16 bytes)

The latest versions of cloudprober armv7 have problems with icmp tests. What could this be related to?

**v0.11.9**

**To Reproduce**

```
test.cfg 
probe {
    name: "icmp_dns_test"
    type: PING
    targets {
    host_names: "1.1.1.1,9.9.9.9"
    }
   interval_msec: 5000  # 5s
   timeout_msec: 1000   # 1s
}
```
```
cloudprober# ./cloudprober -config_file test.cfg  -logtostderr
I0808 08:34:39.174278   22922 prober.go:111] [cloudprober.global] Creating a PING probe: icmp_dns_test
I0808 08:34:39.175383   22922 prometheus.go:186] [cloudprober.prometheus] Initialized prometheus exporter at the URL: /metrics
I0808 08:34:39.175919   22922 probestatus.go:165] [cloudprober.probestatus] Initialized status surfacer at the URL: probesstatus
I0808 08:34:39.177631   22922 sysvars.go:186] [cloudprober.sysvars] 1659936879 labels=ptype=sysvars,probe=sysvars hostname="access" start_timestamp="1659936878" version="v0.11.9"
I0808 08:34:43.918322   22922 prober.go:295] [cloudprober.global] Starting probe: icmp_dns_test
W0808 08:34:48.960235   22922 ping.go:342] [cloudprober.icmp_dns_test] timestamp control message data size (8) is less than timestamp size (16 bytes)
W0808 08:34:48.964727   22922 ping.go:342] [cloudprober.icmp_dns_test] timestamp control message data size (8) is less than timestamp size (16 bytes)
W0808 08:34:48.985619   22922 ping.go:342] [cloudprober.icmp_dns_test] timestamp control message data size (8) is less than timestamp size (16 bytes)
W0808 08:34:48.989977   22922 ping.go:342] [cloudprober.icmp_dns_test] timestamp control message data size (8) is less than timestamp size (16 bytes)
cloudprober 1659936879175480089 1659936889 labels=ptype=sysvars,probe=sysvars hostname="access" start_timestamp="1659936878" version="v0.11.9"
I0808 08:34:49.179533   22922 prometheus.go:261] [cloudprober.prometheus] Checking validity of new label: ptype
cloudprober 1659936879175480090 1659936889 labels=ptype=sysvars,probe=sysvars cpu_usage_msec=175.860
I0808 08:34:49.179723   22922 prometheus.go:261] [cloudprober.prometheus] Checking validity of new label: probe
cloudprober 1659936879175480091 1659936889 labels=ptype=sysvars,probe=sysvars uptime_msec=10214.543 gc_time_msec=0.473 mallocs=22045 frees=10253
I0808 08:34:49.179870   22922 prometheus.go:289] [cloudprober.prometheus] Checking validity of new metric: hostname
cloudprober 1659936879175480092 1659936889 labels=ptype=sysvars,probe=sysvars goroutines=15 mem_stats_sys_bytes=11877372
I0808 08:34:49.180017   22922 prometheus.go:289] [cloudprober.prometheus] Checking validity of new metric: start_timestamp
I0808 08:34:49.180152   22922 prometheus.go:289] [cloudprober.prometheus] Checking validity of new metric: version
I0808 08:34:49.180306   22922 prometheus.go:289] [cloudprober.prometheus] Checking validity of new metric: cpu_usage_msec
I0808 08:34:49.180469   22922 prometheus.go:289] [cloudprober.prometheus] Checking validity of new metric: uptime_msec
I0808 08:34:49.180607   22922 prometheus.go:289] [cloudprober.prometheus] Checking validity of new metric: gc_time_msec
I0808 08:34:49.180738   22922 prometheus.go:289] [cloudprober.prometheus] Checking validity of new metric: mallocs
I0808 08:34:49.180864   22922 prometheus.go:289] [cloudprober.prometheus] Checking validity of new metric: frees
I0808 08:34:49.181004   22922 prometheus.go:289] [cloudprober.prometheus] Checking validity of new metric: goroutines
I0808 08:34:49.181164   22922 prometheus.go:289] [cloudprober.prometheus] Checking validity of new metric: mem_stats_sys_bytes
W0808 08:34:49.921089   22922 ping.go:342] [cloudprober.icmp_dns_test] read udp 0.0.0.0:3: i/o timeout
W0808 08:34:53.960428   22922 ping.go:342] [cloudprober.icmp_dns_test] timestamp control message data size (8) is less than timestamp size (16 bytes)
W0808 08:34:53.964440   22922 ping.go:342] [cloudprober.icmp_dns_test] timestamp control message data size (8) is less than timestamp size (16 bytes)
W0808 08:34:53.985605   22922 ping.go:342] [cloudprober.icmp_dns_test] timestamp control message data size (8) is less than timestamp size (16 bytes)
W0808 08:34:54.022854   22922 ping.go:342] [cloudprober.icmp_dns_test] timestamp control message data size (8) is less than timestamp size (16 bytes)
W0808 08:34:54.921206   22922 ping.go:342] [cloudprober.icmp_dns_test] read udp 0.0.0.0:3: i/o timeout
I0808 08:34:54.921741   22922 prometheus.go:261] [cloudprober.prometheus] Checking validity of new label: dst
I0808 08:34:54.921911   22922 prometheus.go:289] [cloudprober.prometheus] Checking validity of new metric: total
cloudprober 1659936879175480093 1659936893 labels=ptype=ping,probe=icmp_dns_test,dst=1.1.1.1 total=4 success=0 latency=0.000 validation_failure=map:validator,data-integrity:0
I0808 08:34:54.922043   22922 prometheus.go:289] [cloudprober.prometheus] Checking validity of new metric: success
cloudprober 1659936879175480094 1659936893 labels=ptype=ping,probe=icmp_dns_test,dst=9.9.9.9 total=4 success=0 latency=0.000 validation_failure=map:validator,data-integrity:0
I0808 08:34:54.922162   22922 prometheus.go:289] [cloudprober.prometheus] Checking validity of new metric: latency
I0808 08:34:54.922285   22922 prometheus.go:289] [cloudprober.prometheus] Checking validity of new metric: validation_failure
I0808 08:34:54.922428   22922 prometheus.go:261] [cloudprober.prometheus] Checking validity of new label: validator```

cloudprober# cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian

model name      : ARMv7 Processor rev 4 (v7l)

Hardware        : BCM2835
Revision        : a02082
Serial          : 00000000a9eb2a7f
Model           : Raspberry Pi 3 Model B Rev 1.2

```

**Comment by manugarg** [comment]
This error message is coming from here:
https://github.com/cloudprober/cloudprober/blob/2df3af206576e09cfc4d4a5a4ae8223280b92268/probes/ping/icmpconn_unix.go#L157

It seems that SCM_TIMESTAMP control message has less data on armv7.

**Comment by morhold** [comment]
Yes, I saw it in the code. The question is, can this be fixed? There was no such error on older versions, and all the probes that we have installed on raspberry pi3 worked properly. Unfortunately, I don't remember that version.

**Comment by manugarg** [comment]
Initial research suggests that the `timeval` data structure (structure in the SCM_TIMESTAMP control message) is of size 8 (4+4) on ARMv7. Apparently, Unix traditionally used 32-bit for storing time, but most new operating systems use 64-bit now. 

Following page talks about this problem:
https://en.wikipedia.org/wiki/Year_2038_problem

**Comment by manugarg** [comment]
This confirms the suspicion:
https://cs.opensource.google/go/go/+/master:src/runtime/defs_linux_arm.go;l=155;drc=9d34fc5108d91bfcce3c465069dbb2c563af4229
vs
https://cs.opensource.google/go/go/+/master:src/runtime/defs_linux_amd64.go;l=118;drc=9d34fc5108d91bfcce3c465069dbb2c563af4229

I guess we can look at the control message length, and parse it as the older-style 8-byte timeval if its length is 8-byte. Unfortunately I don't have a raspberry pi to test with. I can submit a PR, a binary should be generated by Github Actions which you can use to test with. Will that work for you?

**Comment by manugarg** [comment]
Possible fix:
https://github.com/cloudprober/cloudprober/pull/176

Here are the built binaries with the possible fix:
https://github.com/cloudprober/cloudprober/suites/7709826541/artifacts/322669843

**Comment by morhold** [comment]
Great, everything works!

`./cloudprober -config_file test.cfg  -logtostderr
I0808 11:36:03.763636   29754 prober.go:111] [cloudprober.global] Creating a PING probe: icmp_dns_test
I0808 11:36:03.764930   29754 prometheus.go:186] [cloudprober.prometheus] Initialized prometheus exporter at the URL: /metrics
I0808 11:36:03.765344   29754 probestatus.go:165] [cloudprober.probestatus] Initialized status surfacer at the URL: probesstatus
I0808 11:36:03.766534   29754 sysvars.go:186] [cloudprober.sysvars] 1659947763 labels=ptype=sysvars,probe=sysvars hostname="access" start_timestamp="1659947763" version="v0.11.9-2-g6bfa7a5"
I0808 11:36:07.722666   29754 prober.go:295] [cloudprober.global] Starting probe: icmp_dns_test
cloudprober 1659947763765020110 1659947773 labels=ptype=sysvars,probe=sysvars hostname="access" start_timestamp="1659947763" version="v0.11.9-2-g6bfa7a5"
I0808 11:36:13.768675   29754 prometheus.go:261] [cloudprober.prometheus] Checking validity of new label: ptype
I0808 11:36:13.769383   29754 prometheus.go:261] [cloudprober.prometheus] Checking validity of new label: probe
cloudprober 1659947763765020111 1659947773 labels=ptype=sysvars,probe=sysvars cpu_usage_msec=222.217
cloudprober 1659947763765020112 1659947773 labels=ptype=sysvars,probe=sysvars uptime_msec=10214.280 gc_time_msec=0.846 mallocs=22045 frees=11834
cloudprober 1659947763765020113 1659947773 labels=ptype=sysvars,probe=sysvars goroutines=14 mem_stats_sys_bytes=11877372
I0808 11:36:13.769765   29754 prometheus.go:289] [cloudprober.prometheus] Checking validity of new metric: hostname
I0808 11:36:13.770856   29754 prometheus.go:289] [cloudprober.prometheus] Checking validity of new metric: start_timestamp
I0808 11:36:13.771363   29754 prometheus.go:289] [cloudprober.prometheus] Checking validity of new metric: version
I0808 11:36:13.771843   29754 prometheus.go:289] [cloudprober.prometheus] Checking validity of new metric: cpu_usage_msec
I0808 11:36:13.772315   29754 prometheus.go:289] [cloudprober.prometheus] Checking validity of new metric: uptime_msec
I0808 11:36:13.772466   29754 prometheus.go:289] [cloudprober.prometheus] Checking validity of new metric: gc_time_msec
I0808 11:36:13.772600   29754 prometheus.go:289] [cloudprober.prometheus] Checking validity of new metric: mallocs
I0808 11:36:13.772721   29754 prometheus.go:289] [cloudprober.prometheus] Checking validity of new metric: frees
I0808 11:36:13.772860   29754 prometheus.go:289] [cloudprober.prometheus] Checking validity of new metric: goroutines
I0808 11:36:13.773025   29754 prometheus.go:289] [cloudprober.prometheus] Checking validity of new metric: mem_stats_sys_bytes
cloudprober 1659947763765020114 1659947777 labels=ptype=ping,probe=icmp_dns_test,dst=1.1.1.1 total=4 success=4 latency=158096.995 validation_failure=map:validator,data-integrity:0
I0808 11:36:17.797477   29754 prometheus.go:261] [cloudprober.prometheus] Checking validity of new label: dst
cloudprober 1659947763765020115 1659947777 labels=ptype=ping,probe=icmp_dns_test,dst=9.9.9.9 total=4 success=4 latency=179097.205 validation_failure=map:validator,data-integrity:0
I0808 11:36:17.797670   29754 prometheus.go:289] [cloudprober.prometheus] Checking validity of new metric: total
I0808 11:36:17.797812   29754 prometheus.go:289] [cloudprober.prometheus] Checking validity of new metric: success
I0808 11:36:17.797932   29754 prometheus.go:289] [cloudprober.prometheus] Checking validity of new metric: latency
I0808 11:36:17.798055   29754 prometheus.go:289] [cloudprober.prometheus] Checking validity of new metric: validation_failure
I0808 11:36:17.798195   29754 prometheus.go:261] [cloudprober.prometheus] Checking validity of new label: validator
cloudprober 1659947763765020116 1659947783 labels=ptype=sysvars,probe=sysvars hostname="access" start_timestamp="1659947763" version="v0.11.9-2-g6bfa7a5"
cloudprober 1659947763765020117 1659947783 labels=ptype=sysvars,probe=sysvars cpu_usage_msec=240.036
cloudprober 1659947763765020118 1659947783 labels=ptype=sysvars,probe=sysvars uptime_msec=20213.218 gc_time_msec=0.846 mallocs=22636 frees=11860
cloudprober 1659947763765020119 1659947783 labels=ptype=sysvars,probe=sysvars goroutines=14 mem_stats_sys_bytes=11877372
cloudprober 1659947763765020120 1659947787 labels=ptype=ping,probe=icmp_dns_test,dst=1.1.1.1 total=8 success=8 latency=316165.427 validation_failure=map:validator,data-integrity:0
cloudprober 1659947763765020121 1659947787 labels=ptype=ping,probe=icmp_dns_test,dst=9.9.9.9 total=8 success=8 latency=365925.224 validation_failure=map:validator,data-integrity:0`

**Comment by manugarg** [comment]
Cool. Thanks for confirming. I've merged the pull request. Changes will be available in the ":master" docker image soon. I'll plan for the release, but it that will take at least a week or two.
