### ISSUE TITLE
Support resolving IP Range in RDS client

### ISSUE THREAD

**Issue by ericayyliu** [cloudprober/cloudprober#187]
If the RDS resources' IP is a IP range, e.g. GCP IPv6 forwarding rule, we want the RDS client to parse the cidr and return IP Address.

https://github.com/cloudprober/cloudprober/blob/master/rds/client/client.go#L152

**Comment by manugarg** [comment]
@ericayyliu Can you please share how does this IP appear in the GCE forwarding rules resources? It will also be helpful to understand how are you using Cloudprober.

**Comment by ericayyliu** [comment]
An example IPv6 forwarding-rule
{
  "IPAddress": "fd20:d21:6fe3:3800:0:5:0:0/96",
  "IPProtocol": "TCP",
   "backendService": "https://www.googleapis.com/compute/v1/projects/ilb-ipv6-cep/regions/europe-west1/backendServices/backend-service-eu-w1-cep",
   "ipVersion": "IPV6",
   "kind": "compute#forwardingRule",
   "loadBalancingScheme": "INTERNAL",
   "name": "forwarding-rule-eu-w1-cep",
   "network": "https://www.googleapis.com/compute/v1/projects/ilb-ipv6-cep/global/networks/net-eu-w1-cep",
   "networkTier": "PREMIUM",
   "ports": [
          "80"
    ],
  "region": "https://www.googleapis.com/compute/v1/projects/ilb-ipv6-cep/regions/europe-west1",
   "selfLink": "https://www.googleapis.com/compute/v1/projects/ilb-ipv6-cep/regions/europe-west1/forwardingRules/forwarding-rule-eu-w1-cep",
   "subnetwork": "https://www.googleapis.com/compute/v1/projects/ilb-ipv6-cep/regions/europe-west1/subnetworks/subnet-eu-w1-cep"
 }

**Comment by ericayyliu** [comment]
When I run the ./cloudprober locally, in this code path, https://github.com/cloudprober/cloudprober/blob/master/rds/client/client.go#L152, when the IPAddress is a cidr range, the net.ParseIP will return nil, and it falls back to the dnsResolver

**Comment by manugarg** [comment]
@ericayyliu Ack. I'll try to send a fix. Just curious, are you using it at Google? :)

**Comment by manugarg** [comment]
I think https://github.com/cloudprober/cloudprober/pull/188 should help.

**Comment by ericayyliu** [comment]
Thank you so much @manugarg for fixing this instantly! Yes I am working in Google now :)

**Comment by ericayyliu** [comment]
Actually when I was debugging this for the first time I thought the issue could be in https://github.com/cloudprober/cloudprober/blob/master/targets/gce/forwarding_rules.go#L76, because here it doesn't parse CIDR either. So I am wondering if we will need to fix that also.

**Comment by manugarg** [comment]
> Thank you so much @manugarg for fixing this instantly!

Thank you for debugging. Fix was rather simple.

> Actually when I was debugging this for the first time I thought the issue could be in https://github.com/cloudprober/cloudprober/blob/master/targets/gce/forwarding_rules.go#L76, because here it doesn't parse CIDR either. So I am wondering if we will need to fix that also.

That's the old way of expanding forwarding rules. I didn't get a chance to fully remove it, or implement it through RDS like how I did it for GCE instances. If you're using `rds_targets {}` you should be good. Can you confirm?

**Comment by ericayyliu** [comment]
Yes we are using the rds_target, and inside the config we specify the forwarding_rule path and name etc.

**Comment by manugarg** [comment]
Cool. You should be all set then.

**Comment by ericayyliu** [comment]
Great to know that!

**Comment by manugarg** [comment]
@ericayyliu Closing this issue. Please feel free to reopen if problem continues.
