### ISSUE TITLE
[k8s rds] Resources discovered on k8s use made up names and not IPs for probing

### ISSUE THREAD

**Issue by pugmajere** [cloudprober/cloudprober#196]
**Describe the bug**

Discovering endpoint resources on k8s for HTTP probes results in errors like this:

W1021 20:59:13.816516       1 http.go:307] [cloudprober.sdc-service-edge] Target:edge_10.10.88.28_service-discovery, URL:https://edge_10.10.88.28_service-discovery:9090/ready, http.doHTTPRequest: Get "https://edge_10.10.88.28_service-discovery:9090/ready": dial tcp: lookup edge_10.10.88.28_service-discovery on 169.254.20.10:53: no such host

This name isn't resolvable, and appears to be made up by Cloudprober. There don't appear to be any options to just use the discovered IP, rather than the resource name. ("resource" in this case refers to the internal Cloudprober concept of "endpoint resources", and not anything directly k8s related, as far as I can tell.)

**Cloudprober Version**

v0.11.9 I think.

**To Reproduce**
(slightly simplified config; I dropped some filters and some of the templates being expanded here.)

```
probe {
    type: HTTP
    name: "my_service"
    targets {
        rds_targets {
            resource_path: "k8s://endpoints"
        }
    }
    interval: "30s"
    timeout: "5s"
    {{template "standard_latency_options" .}}

    http_probe {
        protocol: HTTPS
        relative_url: "/ready"
        port: 9090
    }

    validator {
        name: "status_code_2xx"
        http_validator {
            success_status_codes: "200-299"
        }
    }

    validator {
        name: "OK?"
        regex: "LIVE"
    }

}

rds_server {
  provider {
    kubernetes_config {
      endpoints {}
    }
  }
}

```

**Comment by manugarg** [comment]
Actually there is an easy fix for it (we should not even required that fix though, I'll see how we can do that), you just need to add the following field to http_probe stanza:

https://github.com/cloudprober/cloudprober/blob/5128a133a11a9cd51c1d63f02b9131be370a28ae/probes/http/proto/config.proto#L43

**Comment by pugmajere** [comment]
Nice. I'll try that now.

**Comment by manugarg** [comment]
> (we should not even required that fix though, I'll see how we can do that), 

Filed #197 for this.

**Comment by manugarg** [comment]
@pugmajere, Ryan, did it work?

**Comment by manugarg** [comment]
I tested #198 in a local cluster and it's working as expected.

@pugmajere I noticed you're specifying port inside http_probe. You can skip that. Cloudprober will just use the endpoint's port if port is not configured.

**Comment by pugmajere** [comment]
Yeah, it's working now. Thanks!)
