### ISSUE TITLE
Cloudprober on Google Cloud Run

### ISSUE THREAD

**Issue by michaelsatanovsky** [cloudprober/cloudprober#206]
I have been trying to set up Cloudprober to run on Google Cloud's Cloud Run from the image listed on docker. However, I've run into issues with it. 

I get a general error:
`The user-provided container failed to start and listen on the port defined provided by the PORT=9313 environment variable.` 

And more specific errors within the logs:
`cloudprober.go:134] Error reading config from metadata. Err: metadata: GCE metadata "project/attributes/cloudprober_config" not defined`

`logger.go:205] [cloudprober.sysvars] Error getting instance name on GCE: metadata: GCE metadata "instance/name" not defined`

`cloudprober.go:182] Error initializing cloudprober. Err: sysvars_gce: error while getting internal_ip from metadata: metadata: GCE metadata "instance/network-interfaces/0/ip" not defined"`

The "[How-Tos - Running on Kubernetes](https://cloudprober.org/how-to/run-on-kubernetes/)" page on Cloudprober's website is helpful for setting up Cloudprober on GKE, but it is a bit overkill for some users (customers of a Google Cloud service). Would it be possible to add similar support for Cloud Run (or point me to some tools to debug this)?

**Comment by manugarg** [comment]
@michaelsatanovsky thanks for reporting this.

There is a workaround for this. You can add the following flag to the command line to disable getting cloud metadata: `--cloud_metadata=none`.

This error is coming from the fact Cloudprober is discovering it's running on Google cloud, but it's not able to get certain metadata variables. On kubernetes we return early: https://github.com/cloudprober/cloudprober/blob/7d1085c3161c24215864dfee984b424076834bd4/sysvars/sysvars_gce.go#L66.

If we can easily identify that we're running on Cloud Run we can make this more automatic. I'll look into that.

**Comment by michaelsatanovsky** [comment]
Hi @manugarg,

Thanks for following up on this! I was unable to get Cloudprober to run on Cloud Run as it seemed to require access to other cloud metadata. I ended up using a VM instance. Should Cloudprober work with Cloud Run after this fix?

Thanks again!

**Comment by manugarg** [comment]
Hello, @michaelsatanovsky 

This change has not been released yet. If you want to test before the release, you can use the docker image tag - "master". Let me know if that doesn't work as well.

**Comment by manugarg** [comment]
I see. Thanks for retrying it. I'll take another look.

**Comment by manugarg** [comment]
Sorry for the delay. I found the issue and submitted the fix:
https://github.com/cloudprober/cloudprober/pull/228

"master" image should work on Cloud Run now. Would you be able to give it another try? Thanks in advance!

**Comment by michaelsatanovsky** [comment]
This seems promising after some preliminary testing. I'll continue looking at it in more depth over the next couple days.

Thanks!

**Comment by manugarg** [comment]
Thanks for checking, @michaelsatanovsky! Closing this now; feel free to reopen if you encounter an issue again.
