### ISSUE TITLE
negative gauge value not supported for external probes

### ISSUE THREAD

**Issue by matrog** [cloudprober/cloudprober#217]
the external probe does not support negative gauge values which is an issue since a negative value is totally accepted in prometheus gauge definition

https://prometheus.io/docs/concepts/metric_types/

and float64 of course supports negative values.

Why this limitation in Cloudprober?

I would like to measure temperature which can go under 0 but it's currently not possible.

metrics/metrics.go
```
        // A float value
        case '0' <= c && c <= '9':
                f, err := strconv.ParseFloat(val, 64)
                if err != nil {
                        return nil, err
                }
                return NewFloat(f), nil

```

here's my logs

```
W1114 13:57:07.779486    9205 payload.go:267] [cloudprober.test] could not parse value (-1.0) for the new metric name (mytest): unknown value type
```

**Comment by manugarg** [comment]
This is an interesting scenario. We don't even parse negative values:
https://github.com/cloudprober/cloudprober/blob/d3c7f47a9c2fbb1d9ba716da4467c8340c70ea4e/metrics/metrics.go#L49

I'll try to fix it soonish.

**Comment by matrog** [comment]
Thanks @manugarg
