### ISSUE TITLE
README.md uses outdated StackDriver term

### ISSUE THREAD

**Issue by fguendling** [cloudprober/cloudprober#220]
Hi, I immediately get the feeling that something is outdated when I read StackDriver. I propose changing the text in the picture and the text in the README.md to Operations Suite. I would proceed with a PR if you give me a thumbs up?

**Comment by manugarg** [comment]
I've updated it to show Google Cloud Monitoring as well -- sorry, Operation Suite is so unrecognizable, and most folks still use the term Stackdriver for Google Cloud's monitoring offering.
