### ISSUE TITLE
Add a schedule window option to define when the probes should run 

### ISSUE THREAD

**Issue by syd20** [cloudprober/cloudprober#221]
Currently the probes run 24x7 at the intervals defined in the config file. It would be good to have a means to scheduled the time window when this probe should run. Assuming some workloads are unavailable / shutdown at specific time eg. weekends, I would not want cloudprober to reach out to those URL's

**Comment by manugarg** [comment]
This is an interesting idea, @syd20. I'll look into it.

**Comment by syd20** [comment]
@manugarg Any plans to rollout this feature?

**Comment by manugarg** [comment]
@syd20 I was thinking of implementing this. Any suggestions on how the schedule window should be defined?

**Comment by syd20** [comment]
The schedule window could be defined in Cron format and it should be a list to support multiple schedules. 

eg. If I need a maintenance schedule from Friday 2200 hrs to Monday 06 hrs, I could provide it as three schedules - one for Friday, one for Saturday & Sunday and another for Monday.

**Comment by manugarg** [comment]
Thanks for feedback! I am thinking of a slightly different way which might be more appropriate here:
https://github.com/cloudprober/cloudprober/pull/652/files#diff-ef0f1d188969f808c622e42927a3c085fe5130efb88e53cfbc74b16456e67766R195

Example:
```
  //   schdule {
  //     type: DISABLE
  //     start_weekday: FRIDAY
  //     start_time: "22:00"
  //     end_weekday: SUNDAY
  //     end_time: "17:00" 
  //     timezone: "America/New_York"
  //   }
```

**Comment by syd20** [comment]
The format looks good. Im assuming "repeated Schedule" means it supports configuring multiple schedules

**Comment by syd20** [comment]
Just thinking  about the other possible scenarios. If I need a test to run only during the weekdays and working hours, would it mean schedule needs to be defined multiple times, one each for the working day and another for the weekend?

**Comment by manugarg** [comment]
> Just thinking about the other possible scenarios. If I need a test to run only during the weekdays and working hours, would it mean schedule needs to be defined multiple times, one each for the working day and another for the weekend?

For this, better way will be to disable the probe for the night time. Here is an example:
https://github.com/cloudprober/cloudprober/blob/eac7a82e636cf4bbf52e8e6bf2342d60b2271a27/probes/options/schedule_test.go#L48

We can probably define shortcuts like EVERY_WEEKDAY for these kind of scenarios.

> The format looks good. Im assuming "repeated Schedule" means it supports configuring multiple schedules

Yes, multiple schedules are supported.

**Comment by manugarg** [comment]
Added a couple of examples as well:
https://github.com/cloudprober/cloudprober/pull/683
