### ISSUE TITLE
Customize monitoringURL prefix for Stackdriver metrics

### ISSUE THREAD

**Issue by kushal288** [cloudprober/cloudprober#261]
We are currently exporting metric suing stackdriver surfacer in format
 `<monitoring_url>/<ptype>/<probe>/<metric>`
however we want to have metrics in the format  
`<monitoring_url>/<metric>`
as we are running multiple copies of same probe. This will help in collect a single metric from multiple probes.
We can use ptype and probe name as labels instead, for cache key.

**Comment by kushal288** [comment]
Comment from Manu over email - 
_Regarding the monitoring URL, I am okay with optionally dropping ptype and probe from the URL. I am wondering what the option should be? Ideally it could just be a template, but then we'll have to handle template parsing. Something like metric_name_template = `"<ptype>/<probe>/<name>"` (default .. one could change it to just `<name>`) . Does that make sense? Did you have something simpler in mind?_

**Comment by kushal288** [comment]
@manugarg I was thinking to have a more simple approach for it, basically creating 2 config flags in stackdriver surfacer proto definition -
excludeProbeNameFromMetricPrefix [default=False]
excludeProbeTypeFromMetricPrefix [default=False]

Using templating for it might be prone to error for configuration, and also during parsing we will need to validate the valid keys.

What do you think?
If this sounds good I will create a PR.

**Comment by manugarg** [comment]
I agree template will make it more complicated. What do you think about defining an enum like this:
```
enum MetricPrefix {
  UNDEFINED = 0;       
  NONE = 1;         // metric_name
  PTYPE_PROBE = 2;  // ptype/probe/metric_name
  PROBE = 3;        // probe/metric_name
}
optional MetricPrefix metric_prefix = ..
```
One advantage I see of this approach is that it makes it more clear what metric prefix looks like, in one place.

**Comment by kushal288** [comment]
This looks better! I will make these changes.
