### ISSUE TITLE
Add a test to verify that all probe types allow empty configs.

### ISSUE THREAD

**Issue by manugarg** [cloudprober/cloudprober#293]
TCP probe crashes if we don't provide a config (that's because we try to access a field of the config)  -- fix #292.  We ran into this problem with HTTP probe sometime back. We should a add a test that verifies that all probe types allow empty configs.

**Comment by robpickerill** [comment]
Manu, would you be able to check that #544 achieves what you wanted here. Thanks!

**Comment by manugarg** [comment]
@robpickerill Thanks for implementing this.
