### ISSUE TITLE
Support specifying prober interval / timeouts as durations

### ISSUE THREAD

**Issue by manugarg** [cloudprober/cloudprober#3]
Copied from https://github.com/google/cloudprober/issues/611, originally filed by @vadimberezniker.

It would be nice if the prober config supported specifying durations as user-friendly strings.
i.e.
```
interval: "10m" 
timeout: "15s"
```
instead of
```
interval_msec: 600000  # 10m
timeout_msec: 15000   # 15s
```

+1ed by @benner @manugarg

**Comment by nvidyala** [comment]
@manugarg I'd like to pick this up, could you please assign the issue to me?

**Comment by manugarg** [comment]
@nvidyala Done. Thanks for picking this up.
