### ISSUE TITLE
Please migrate from lib/pq to pgx

### ISSUE THREAD

**Issue by asuffield** [cloudprober/cloudprober#300]
https://github.com/cloudprober/cloudprober/blob/master/surfacers/postgres/postgres.go uses lib/pq, which is effectively abandoned in favour of https://github.com/jackc/pgx - should be a simple migration, just change the library and driver name passed to sql.Open.

**Comment by manugarg** [comment]
Thanks for filing this @asuffield. I started working on this here: https://github.com/cloudprober/cloudprober/pull/305. I think as a result of this, we'll probably end up restructuring postgres surfacer a bit, because pgx is not a drop-in replacement for pq.

**Comment by manugarg** [comment]
This is done: #305.
