### ISSUE TITLE
Issues with TLS for GRPC Probe

### ISSUE THREAD

**Issue by zmailloux** [cloudprober/cloudprober#307]
**Describe the bug**
Hello Manu! I'm trying to use the GRPC probe type and had been running into problems and ultimately came up with a workaround, but I was hoping to revisit it and see if you had any ideas. I have a the following two gRPC health probes, one uses an external CLI I have loaded onto the container, and another uses the GRPC probe type within cloudprober. In the example below, "grpc probe v1" works, and "grpc probe v2" does not. It has been like this for quite some time now, and I've verified that they are hitting the same address by the log message.

**Cloudprober Version**
1.25.0

**To Reproduce**
```probe {
    type: EXTERNAL
    name: "grpc probe v1"
    targets {   
        k8s {
            endpoints: "server"
            namespace: "sample"
            portFilter: "service-discovery-ssl"
        }
    }

    interval: "30s"
    timeout: "5s"

    latency_unit: "s"
    latency_metric_name: "latency_dist"

    latency_distribution {
      explicit_buckets: "0.01,0.1,0.15,0.2,0.25,0.35,0.5,0.75,1.0,1.5,2.0,3.0,4.0,5.0,10.0,15.0,20.0"
    }

    external_probe {
      command: "grpc_health_probe -addr=@address@:@port@ -tls -tls-ca-cert=/shared/pki/root_ca.pem -tls-client-cert=/shared/pki/leaf_intermediate_chain.pem -tls-client-key=/shared/pki/private_key.pem -tls-server-name=global.identity"
    }
}

probe {
    type: GRPC
    name: "grpc probe v2"
    targets {
        k8s {
            endpoints: "server"
            namespace: "sample-app"
            portFilter: "service-discovery-ssl"
        }
    }
    interval: "10s"
    timeout: "5s"

    grpc_probe {
        method: HEALTH_CHECK
        tls_config {
          ca_cert_file: "/shared/pki/root_ca.pem",
          tls_cert_file: "/shared/pki/leaf_intermediate_chain.pem",
          tls_key_file: "/shared/pki/private_key.pem",
          server_name: "global.identity"
        }
        health_check_ignore_status: false
    }

    latency_unit: "s"
    latency_metric_name: "latency_dist"

    latency_distribution {
      explicit_buckets: "0.01,0.1,0.15,0.2,0.25,0.35,0.5,0.75,1.0,1.5,2.0,3.0,4.0,5.0,10.0,15.0,20.0"
    }
}
sysvars_interval_msec: 60000

surfacer {
    type: PROMETHEUS

    prometheus_surfacer {
      metrics_prefix: "cloudprober_"
    }
}```

**Additional context**
I've tried variations of `disable_cert_validation` and `health_check_ignore_status` with different values, and every time I still get  the following error back from "grpc probe v2" every time:
`request failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded. ConnState: IDLE. Peer: unknown` 

I'm unclear as to what I'm doing wrong. I'm still learning Golang, but I believe I've read it correctly. If nothing else more examples would be valuable.

**Comment by zmailloux** [comment]
Additionally, separate question, if we wanted to use the GRPC probe in a fashion to a grpcurl command requiring a protobuff file, where would that be passed in? 

For example:
```
grpcurl -d '{"transfer_id": "####-####-####"}' -protoset ./descriptor_set.pb -cacert /shared/pki/root_ca.pem -cert /shared/pki/leaf_intermediate_chain.pem -key /shared/pki/private_key.pem -servername global.identity ip.address:port service.v1.Service/GetTransferStatus
```

**Comment by manugarg** [comment]
Regarding the first question, I think I know what's going on here. We use target name and port to connect to the host and in the case of k8s targets that's no good as most of the k8s targets have derived names (service_endpoint_Port for example):
https://github.com/cloudprober/cloudprober/blob/f1b578ead0f50ca2a3cab3196a5edaefa52a5db6/probes/grpc/grpc.go#L202

We had changed this behavior for HTTP probes some time back (Oct, 2022):
https://github.com/cloudprober/cloudprober/commit/03cda470703acec464edfa9171b7bc449298fb93

We should have changed it for gRPC probes as well. I'll submit a fix for this shortly.

**Comment by manugarg** [comment]
Regarding 2nd question, generic gRPC request is not implemented yet. I started implementing it at one point but didn't finish it. I've filed a separate request for that for now: #308.

**Comment by manugarg** [comment]
Created https://github.com/cloudprober/cloudprober/pull/309 for the 1st issue.

**Comment by zmailloux** [comment]
@manugarg Ah yes I tried it manually and that appears to be the case. Thanks for taking a look!

**Comment by manugarg** [comment]
@zmailloux Zach, if you still care :smile:, generic gRPC request (grpcurl like) support has been added to Cloudprober in #470. Example probe config:

```
 probe {
   name: "grpc_generic"
   type: GRPC
   targets {
     # Hit another cloudprober instance running with grpc_port enabled.
     host_names: "localhost:9314"
   }

   grpc_probe {
     method: GENERIC
     request {
       call_service_method: "cloudprober.Cloudprober.ListProbes"
       body: "{}"
     }
   }

   validator {
      name: "match_probe"
      regex: "ping_google"
   }
 }
 ```
 
Full request config:
https://github.com/cloudprober/cloudprober/blob/715cbe907e3b2d31797ed623bcbce776d8985280/probes/grpc/proto/config.proto#L10

This will go out in the next release: v0.12.9 (targeting Aug 28).
