### ISSUE TITLE
Add unique user-agent to HTTP(S) probes

### ISSUE THREAD

**Issue by zmailloux** [cloudprober/cloudprober#316]
**Describe the feature you'd like and the problem it will solve**
Description of what you want to happen and what problem will it solve for you.

Hello Manu, 

It would be helpful for those debugging to have an option unique value in a `User-Agent` request header on HTTP(S) probes that could be logged to the output in event of probe timeout or failure to assist in debugging on the server side. We've been seeing occasional unusual timeouts to some of our services while using the probes and could use these headers (if logged) to better investigate the issue in the future.

**Comment by manugarg** [comment]
Will something like the following work:
https://github.com/cloudprober/cloudprober/pull/317/files

You'd like it to be logged at the server side, right?

**Comment by manugarg** [comment]
Hey @zmailloux, can you confirm if something like above will be help close this issue?
