### ISSUE TITLE
Some unit tests fail

### ISSUE THREAD

**Issue by FranklinYu** [cloudprober/cloudprober#324]
**Describe the bug**
These two tests fail:
 - `common/oauth/bearer_test.go`: `TestK8STokenSource`
 - `probes/grpc/grpc_test.go`: `TestConnectFailures`

Permanent links for convenience:

https://github.com/cloudprober/cloudprober/blob/4a1cdb897529ca055e3a32e7c35237fdc80ab590/common/oauth/bearer_test.go#L215

https://github.com/cloudprober/cloudprober/blob/4a1cdb897529ca055e3a32e7c35237fdc80ab590/probes/grpc/grpc_test.go#L166

**Cloudprober Version**
Reproducible on both latest release (0.12.6) and the `master` branch. Go compiler 1.20.2 on Linux.

**To Reproduce**
1. At root of the project, run `go test ./common/oauth ./probes/grpc`
2. To run all unit tests: `go test ./...`

**Additional context**
I’m attempting to package the binary on AUR.

**Comment by manugarg** [comment]
Hello @FranklinYu, thanks for reporting this.

So  "common/oauth/bearer_test.go: TestK8STokenSource" has been flaky. The second run always succeeds. That's the reason I never noticed this -- gotestsum was hiding the flakiness. I found the root cause of that fixed it in #325.

**Comment by manugarg** [comment]
However, I am not able to reproduce the "probes/grpc/grpc_test.go: TestConnectFailures" failure. This is one of the successful runs for example:
https://github.com/cloudprober/cloudprober/actions/runs/4604204100/jobs/8134923035

**Comment by FranklinYu** [comment]
`common/oauth/bearer_test.go` passes for me after your fix. Thanks!

As for `probes/grpc/grpc_test.go` I hit this:

```plain
E0404 20:25:52.683298  796233 sysvars.go:63] [nil] Sysvars map is un-initialized. sysvars.Vars() was called before sysvars.Init().
```

Full error message:

```plain
E0404 20:25:51.181908  796233 sysvars.go:63] [nil] Sysvars map is un-initialized. sysvars.Vars() was called before sysvars.Init().
E0404 20:25:52.683298  796233 sysvars.go:63] [nil] Sysvars map is un-initialized. sysvars.Vars() was called before sysvars.Init().
--- FAIL: TestConnectFailures (1.80s)
    grpc_test.go:201:
        	Error Trace:	/tmp/cloudprober/probes/grpc/grpc_test.go:201
        	Error:      	"0" is not greater than or equal to "7"
        	Test:       	TestConnectFailures
        	Messages:   	message#: 0, total, em: 1680665153 labels=ptype=grpc,probe=grpc-connectfail,dst=localhost:9 total=0 success=0 =0.000 connecterrors=0
    grpc_test.go:202:
        	Error Trace:	/tmp/cloudprober/probes/grpc/grpc_test.go:202
        	Error:      	"0" is not greater than or equal to "7"
        	Test:       	TestConnectFailures
        	Messages:   	message#: 0, connecterrors, em: 1680665153 labels=ptype=grpc,probe=grpc-connectfail,dst=localhost:9 total=0 success=0 =0.000 connecterrors=0
    grpc_test.go:201:
        	Error Trace:	/tmp/cloudprober/probes/grpc/grpc_test.go:201
        	Error:      	"0" is not greater than or equal to "14"
        	Test:       	TestConnectFailures
        	Messages:   	message#: 1, total, em: 1680665153 labels=ptype=grpc,probe=grpc-connectfail,dst=localhost:9 total=0 success=0 =0.000 connecterrors=0
    grpc_test.go:202:
        	Error Trace:	/tmp/cloudprober/probes/grpc/grpc_test.go:202
        	Error:      	"0" is not greater than or equal to "14"
        	Test:       	TestConnectFailures
        	Messages:   	message#: 1, connecterrors, em: 1680665153 labels=ptype=grpc,probe=grpc-connectfail,dst=localhost:9 total=0 success=0 =0.000 connecterrors=0
E0404 20:25:54.484846  796233 sysvars.go:63] [nil] Sysvars map is un-initialized. sysvars.Vars() was called before sysvars.Init().
E0404 20:25:55.985486  796233 sysvars.go:63] [nil] Sysvars map is un-initialized. sysvars.Vars() was called before sysvars.Init().
FAIL
FAIL	github.com/cloudprober/cloudprober/probes/grpc	7.627s
FAIL
```

So it is

https://github.com/cloudprober/cloudprober/blob/4a1cdb897529ca055e3a32e7c35237fdc80ab590/probes/grpc/grpc_test.go#L201-L202

and

https://github.com/cloudprober/cloudprober/blob/a66948712b39218f637ee0f72a0b12b61241ab31/sysvars/sysvars.go#L63

This test passes on Debian, so it could be specific to Arch Linux, though I cannot tell which part of Arch. Also FYI I found some log files in my `/tmp`, but I’m not sure which one to read (there are too many).

**Comment by manugarg** [comment]
Sysvars map error is harmless. It doesn't matter for testing. On Arch Linux, you're not seeing expected metrics when connecting to an invalid host port (port 9 is the discard port). For some reason context is not timing out. Where are you running your test -- local or on a VM (where timing based tests may be flaky for resources reasons).

Since this is just a connect failure test, can you ignore it during your package build?

**Comment by FranklinYu** [comment]
The Arch Linux runs in a laptop (bare-metal).

If this test is deemed optional, then it makes sense to skip it in packaging. How would you recommend we skip it? If I simply do `-skip TestConnectFailures`, would it accidentally skip this name in other files as well?

**Comment by manugarg** [comment]
Yeah, it should be safe to skip it.

Since the failure is only on Arch Linux, I am not sure if it's worth it to fix it. Also, I don't have a way to replicate it as I don't have a machine running Arch Linux.

Using skip flag SGTM.

**Comment by FranklinYu** [comment]
Thanks!
