### ISSUE TITLE
Add Open Telemetry Surfacer

### ISSUE THREAD

**Issue by icco** [cloudprober/cloudprober#326]
https://opentelemetry.io/ is supported by most observability providers, and has an easy to use Go interface for metrics. It could even be used to merge with the prometheus surfacer to simplify code.

**Comment by manugarg** [comment]
We'll still need to implement caching for either EventMetrics or ScopeMetrics, and whenever Produce is called (presumable by reader) produce data from that caching.

**Comment by manugarg** [comment]
Regarding the metrics conversion, I found opencensus example to be very relevant:
1. Here is how they [create a producer](https://github.com/open-telemetry/opentelemetry-go/blob/2e54fbb3fede5b54f316b3a08eab236febd854e0/bridge/opencensus/metric.go#L49).
    Note: They are using library name as scope name. We can use something like "github.com/cloudprober/cloudprober"

2. Here is how they [convert the OC metrics into OTEL metrics](
    https://github.com/open-telemetry/opentelemetry-go/blob/2e54fbb3fede5b54f316b3a08eab236febd854e0/bridge/opencensus/internal/ocmetric/metric.go#L39).

3. This is how they convert [metrics data into data points](https://github.com/open-telemetry/opentelemetry-go/blob/2e54fbb3fede5b54f316b3a08eab236febd854e0/bridge/opencensus/internal/ocmetric/metric.go#L98).

They seem to be using actual metric name as [Metric.Name](https://github.com/open-telemetry/opentelemetry-go/blob/2e54fbb3fede5b54f316b3a08eab236febd854e0/bridge/opencensus/internal/ocmetric/metric.go#L52).

**Comment by manugarg** [comment]
I've finally started working on it. I'll send a PR soon.

**Comment by manugarg** [comment]
PR: #642

**Comment by manugarg** [comment]
This has been released: https://github.com/cloudprober/cloudprober/releases/tag/v0.13.2

There may still be rough edges but I've tested it quite a bit over last few days.
