### ISSUE TITLE
Question - Is there a way to disable printing cloudprobe metrics to sdtout?

### ISSUE THREAD

**Issue by rsvalerio** [cloudprober/cloudprober#36]
I have a log collector that captures and I would like to avoid filtering it there, but instead, disable it in cloudprobe side, because metrics are escraped by prometheus already

Thanks

**Comment by manugarg** [comment]
Yes. Cloudprober has this concept of surfacers: https://cloudprober.org/surfacers/overview/. By default it enables "prometheus" and "file" surfacers, and "file" surfacer writes to stdout by default. You can disable metrics to stdout by adding this to your config:

```
surfacer {
  type: PROMETHEUS
}
```

Explicitly specifying a surfacer disables the default behavior.

**Comment by rsvalerio** [comment]
Thank you @manugarg 
closing it
