### ISSUE TITLE
[alerting] Implement PagerDuty notifications.

### ISSUE THREAD

**Issue by manugarg** [cloudprober/cloudprober#390]

**Comment by robpickerill** [comment]
hey Manu, I hope you are well.

Would it help you if I picked up some of these alerting issues?

**Comment by robpickerill** [comment]
No problems at all, I'll keep an eye on your progression and when you've got the scaffolding you want, I'll pick a few issues up.

If there is anything else that you'd like me to pick up in the mean time please let me know

**Comment by manugarg** [comment]
We should use a config like this for pagerduty:
https://prometheus.io/docs/alerting/latest/configuration/#pagerduty_config

We'll most likely use the events API:
https://developer.pagerduty.com/docs/ZG9jOjExMDI5NTgx-send-an-alert-event

**Comment by robpickerill** [comment]
Thanks @manugarg - I can pick this up if it's still free. 

Events v2 is good.

**Comment by manugarg** [comment]
Thanks @robpickerill! That will be great.

**Comment by manugarg** [comment]
Marking it closed as it's done.
