### ISSUE TITLE
Flags are not being parsed for running external command

### ISSUE THREAD

**Issue by Pulkit0110** [cloudprober/cloudprober#393]
**Describe the bug**
While running probe of type EXTERNAL with command that passes in few flags but none of the flags are being parsed. Instead of the flags only whitespaces are getting passed.

**Cloudprober Version**
Pre-release (latest changes)

**To Reproduce**
Attached the scripts for reference

**Additional context**
[cloudprober.zip](https://github.com/cloudprober/cloudprober/files/11552236/cloudprober.zip)

**Comment by manugarg** [comment]
I could reproduce this bug. Thank you so much for filing this, @Pulkit0110. It was a recent change where I was trying to optimize label substitution in command args. 

I've created #394 to fix the bug and fix/add a test that would have caught this error.
