### ISSUE TITLE
Add support for JSON logs

### ISSUE THREAD

**Issue by icco** [cloudprober/cloudprober#406]
I would love if there were a JSON log formatting option. Logs are currently plain strings which can be hard to dynamically parse with some services.

**Comment by manugarg** [comment]
#462 may fix this. Not committed yet.

**Comment by manugarg** [comment]
@icco This is done in the code in the repo. You can use the flag `--logfmt=json` flag to export logs in JSON format.
Ways to use this unreleased version: "main" docker tag, or the "tip" release.

**Comment by icco** [comment]
Thanks we're rolling it out today!
