### ISSUE TITLE
Support for checking and comparing value in Last-Modified Header

### ISSUE THREAD

**Issue by syd20** [cloudprober/cloudprober#414]
**Support for checking and comparing Last-Modified Header**

I would like to see an additional validation based on Last Modified Header where I compare the value against the input value. It should return a successful validation if the difference is within the specified input duration else a failed validation. Based on documentation, success_header option in validator checks for specific time stamp and not the difference between current time and last modified time

**Comment by manugarg** [comment]
@syd20 Can you please also add a use case that would require such a validation?

**Comment by syd20** [comment]
I need to configure probes where I look up the value in Last Modified header, and need to check if the Last Modified time is greater than x seconds/ minutes as compared to the current time. This is solely for verifying if the content had been updated or is stale. The duration difference ( in seconds or minutes) would  be specified in configuration file and could vary for different checks. Check is treated a failure if the Last Modified value exceeds the duration specified.

**Comment by syd20** [comment]
Thanx for the rolling out this change.
