### ISSUE TITLE
"resp-code" metric of HTTP probe can change in surfacer

### ISSUE THREAD

**Issue by jinmeiib** [cloudprober/cloudprober#423]
**Describe the bug**
I'm not sure if this is intentional or a bug, but this is the description:
The "resp-code" metric of an HTTP probe passed to a surfacer may be different from the metric at the time the event is created

**Cloudprober Version**
0.12.6, but the behavior seems to be the same on master as of commit 8056812.

**To Reproduce**
1. configure an http probe, e.g., with the following parameter:
```
  interval_msec: 2000  # 2s
  timeout_msec: 1000   # 1s
  stats_export_interval_msec: 2000
```
2.  write a custom surfacer that simply prints the event metrics with some delay:
```
func (s *mySurfacer) Write(ctx context.Context, em *metrics.EventMetrics) {
    time.Sleep(5 * time.Second)
    fmt.Printf("event metrics: %v\n", em)
}
```
3. Run the prober.  Then, on the first call on `Write`, you'll see something like:
```
event metrics: ...total=1 success=1 latency=712057.779 timeouts=0 resp-code=map:code,200:3
```
I'm afraid this is confusing, since it looked like there were 3 responses (of code 200) while the total in the metric is 1.
Is this an intentional behavior for some specific reason?

**Additional context**
I've not tested it, but from code inspection, the same possible issue can happen for "resp-body" and "validation_failure" metrics.

If this is not intentional, one obvious fix is to clone the resp code map to be added to the event metrics:
```
	em := metrics.NewEventMetrics(ts).
		AddMetric("total", metrics.NewInt(result.total)).
		AddMetric("success", metrics.NewInt(result.success)).
		AddMetric(p.opts.LatencyMetricName, result.latency).
		AddMetric("timeouts", metrics.NewInt(result.timeouts)).
		AddMetric("resp-code", result.respCodes.Clone()) // make a clone of respCodes
```

**Comment by manugarg** [comment]
Thanks for the bug report @jinmeiib!

I am not sure what's going on here, but I am unable to reproduce this with the stock surfacers:
```
[samwise 15:51:51 ~/code/cloudprober(master)]$ go run ./cmd/. --config_file ~/cloudprober_423.cfg
cloudprober 1690411914404336026 1690411914 labels=ptype=http,probe=http,dst=www.google.com total=1 success=1 latency=227840.744 timeouts=0 resp-code=map:code,200:1
cloudprober 1690411914404336027 1690411916 labels=ptype=http,probe=http,dst=www.google.com total=2 success=2 latency=445231.768 timeouts=0 resp-code=map:code,200:2
cloudprober 1690411914404336028 1690411918 labels=ptype=http,probe=http,dst=www.google.com total=3 success=3 latency=677097.716 timeouts=0 resp-code=map:code,200:3
cloudprober 1690411914404336029 1690411920 labels=ptype=http,probe=http,dst=www.google.com total=4 success=4 latency=893131.345 timeouts=0 resp-code=map:code,200:4
```

Config file:
```
[samwise 15:52:01 ~/code/cloudprober(master)]$ cat ~/cloudprober_423.cfg
probe {
  type: HTTP
  name: "http"

  interval_msec: 2000  # 2s
  timeout_msec: 1000   # 1s
  stats_export_interval_msec: 2000

  targets {
    host_names: "www.google.com"
  }
}
```
I see the same behavior in the prometheus surfacer.

I'll also try with a custom surfacer, like the one you shared in the example. In the meantime, can you please share if there is something specific in your config that might be causing it.

**Comment by manugarg** [comment]
That said though, I agree that we should clone respCodes (and other similar params) before attaching them to the EventMetrics. I'll take a deeper look.

**Comment by jinmeiib** [comment]
> can you please share if there is something specific in your config that might be causing it.

The key is `time.Sleep` in the snippet surfacer code:
```
    time.Sleep(5 * time.Second)
```
It emulates a slow surfacer, sleeping longer than the probe interval. So, by the time `fmt.Printf` is called, there have been several more probe attempts in the probe goroutine and the resp_code map has been updated. Since the resp_code map is shared between the probe and surfacer, the surfacer sees the updated counter. Cloning the map before publishing would prevent that.

This is, of course, a stupid example, but should highlight other subtle cases like some very short probe interval with a relatively slow surfacer.

**Comment by manugarg** [comment]
Yeah, I was about to respond with that. It most likely impacts only slow surfacers. The only reason to not clone will be to save on memory creation/deletion.

Cloning will be the right thing to do, but just for curiosity, are you observing this behavior in real-world?

**Comment by jinmeiib** [comment]
> are you observing this behavior in real-world?

No, I've not seen it in real-world. I'm working on writing a custom surfacer that would inspect the resp-code metrics, and noticed this possible issue while looking at how this metric is delivered from the probe to the surfacer.

**Comment by manugarg** [comment]
#437 fixes this issue, but I'd like to make it clear that this bug is extremely unlikely to impact the stock surfacers.
