### ISSUE TITLE
Add dedicated readiness and liveness probe endpoints

### ISSUE THREAD

**Issue by ashi009** [cloudprober/cloudprober#430]
**Describe the feature you'd like and the problem it will solve**

When running on k8s, we would love to have dedicated endpoints for readiness/liveness probes. 

For now the options are /status and /metrics. Both are quite heavy when many probers are configured.

Also, we would love to avoid scraping it (when using prometheus) when there is no data. eg. not returning ok from readiness endpoint until we probed all targets for once.

**Comment by manugarg** [comment]
Handler for readiness and liveness probes sounds reasonable to me. #435 will do that.

However, waiting for the first target to report before enabling health handler is hard to implement and also doesn't align with the concept of liveness/readiness.

**Comment by ashi009** [comment]
> However, waiting for the first target to report before enabling health handler is hard to implement and also doesn't seem to align with the concept of liveness/readiness.

I think it aligns with the concept of readiness probe (letting Kubernetes know when your app is ready to serve traffic), given cloudprober is part of the monitoring system, and it's solo purpose is to give meaningful/correct data for other monitoring systems. 

However, I took a closer look to the [Surfacer interface](https://github.com/cloudprober/cloudprober/blob/c33bd1a5334218f7819a2798e602425c09d88e96/surfacers/surfacers.go#L101), apparently prometheus surfacer doesn't surface any incomplete data until a event is actually recorded.  Which is much better comparing to the default prometheus client [behavior](https://prometheus.io/docs/practices/instrumentation/#avoid-missing-metrics) which exports a zero value for any declared metrics once the server is up. So the current implementation guarantees that only correct data is surfaced, therefore a simple 200 OK handler will be just fine.

IMHO this should be be documented somewhere to make sure this is a feature instead of a implementation detail.

**Comment by manugarg** [comment]
Thanks for taking a deeper look @ashi009, and thoughtful review and comments. Much appreciated.

#435 will go out in the next release, scheduled for Aug 20 right now. In the meantime, you can use the release built from the HEAD (:main docker tag and 'tip' pre-release).
