### ISSUE TITLE
Split config into multiple files 

### ISSUE THREAD

**Issue by syd20** [cloudprober/cloudprober#484]
I would like to have the option to split the config into multiple files - as in multiple files in a directory. Currently I have a dynamic setup on EKS where I have multiple probes defined and changes to one requires me to regenerate the config file. Related to this, it would be useful to even be able to reload the config without the need to restart the pod for which I'll file a separate ticket.

**Comment by manugarg** [comment]
Live reload has come up a few times before. I've been reluctant of adding it because clearing a probe's (and other) state cleanly on its removal was not very well implemented. We've certainly improved in that area quite a bit and can look at it again.

**Comment by manugarg** [comment]
FYI,

I am working on adding the include file support here: https://github.com/cloudprober/cloudprober/pull/643

You'll be able to create a top level file that includes other files. Example:

-- cloudprober.cfg --
include "cloudprober.d/team1.cfg"
include "cloudprober.d/team2.cfg"
include "cloudprober.d/team3.cfg"


@syd20 can you please change this ticket to just be multiple files, and file a separate one for reload config?

**Comment by syd20** [comment]
Changed the scope of ticket to create multiple config files

**Comment by manugarg** [comment]
I've added multiple config files support to cloudprober helm-charts as well:
https://github.com/cloudprober/helm-charts/pull/28

Closing it now. I'll cut a new release next week.
