### ISSUE TITLE
Metric for response body size

### ISSUE THREAD

**Issue by syd20** [cloudprober/cloudprober#508]
I did't find anything in the document about a metric for response size? Can we have a metric for emitting the response body size? I have a use case where I would like to check the content length and configure alerting if it's below the threshold

**Comment by manugarg** [comment]
I think tracking individual use case like this is not going to work well. I'm trying to think of some generic approach to validators.

**Comment by syd20** [comment]
Here I would not require a validator but just the response body size to be sent as a metric similar to those for latency and status codes. I do agree we would need some generic long term approach for validator especially where we need some dynamic comparison

**Comment by manugarg** [comment]
Adding a new metric is expensive in the sense that it affects everyone automatically, so we don't do that unless it's something that applies to a lot of use cases, and there is a significant demand for it.

Validators are less invasive as you have to explicitly enable them. One thing we can add to validators is an option to mark probe as success even if that validator fails -- this will allow users to generate/use validator metrics without failing the probe.

Another option we've been thinking of for a while is to generate metrics from HTTP responses: https://github.com/cloudprober/cloudprober/issues/356
We can possibly utilize that option to generate metrics from headers as well.

**Comment by manugarg** [comment]
I am going to merge this into #356.

**Comment by manugarg** [comment]
@syd20 This can now be done (unreleased, but checked in). Please see #841 .

https://cloudprober.org/docs/config/metrics/#cloudprober_metrics_payload_OutputMetricsOptions

You can add something like the following to your config:

```
    response_metrics_options {
      header_metric {
        metric_name: "content-length"
        type: INT
      }
   }
```
