### ISSUE TITLE
Prometheus: Expose individual probe results

### ISSUE THREAD

**Issue by theduke** [cloudprober/cloudprober#510]
Currently the Prometheus surfacer just provides aggregate data. 

It would be great if we could also get an option to provide a metric for each individual executed probe, which is purged once it was exported once.

**Comment by manugarg** [comment]
@theduke You can export gauge metrics instead of aggregates by adding the following to the config:

```
export_as_gauge: true
```
https://cloudprober.org/docs/config/surfacer/#cloudprober_surfacer_SurfacerDef

Note: if you run more than one probe every 10s, you'll still see results aggregated every 10s.

**Comment by manugarg** [comment]
@theduke Can you please confirm if the above comment answers your question?
