### ISSUE TITLE
Update CONTRIBUTING.md following separation from Google

### ISSUE THREAD

**Issue by conallob** [cloudprober/cloudprober#523]
CONTRIBUTING.md still refers to the Google internal codebase as the Source of Truth, etc.

Since cloudprober has evolved into it's own project, perhaps the guidance in CONTRIBUTING.md can be updated for (potential) contributors

**Comment by manugarg** [comment]
Thanks for filing this @conallob. Good call out. I've fixed it.

**Comment by conallob** [comment]
Thank you! An up to date CLA means I can now ask my employer if I can make the occasional contribution :)
