### ISSUE TITLE
Extensions example is not working after update to v0.12.9

### ISSUE THREAD

**Issue by olegmayko** [cloudprober/cloudprober#567]
**Describe the bug**
After updating to latest v0.13 the cloudprober with external probes cannot be started. 

**Cloudprober Version**
v0.13 

**To Reproduce**
1. Try to build  and start the example probe as described in the [doc](https://cloudprober.org/docs/how-to/extensions/#implement-a-cloudprober-binary-that-includes-support-for-our-probe) 
1. See error
```
./myprober flag redefined: logtostderr
panic: ./myprober flag redefined: logtostderr

goroutine 1 [running]:
flag.(*FlagSet).Var(0x140000fe000, {0x10563d570, 0x14000532a90}, {0x104f5c6f5, 0xb}, {0x104fa23f3, 0x54})
	/opt/homebrew/Cellar/go/1.21.1/libexec/src/flag/flag.go:1028 +0x308
flag.(*FlagSet).BoolVar(...)
	/opt/homebrew/Cellar/go/1.21.1/libexec/src/flag/flag.go:749
flag.(*FlagSet).Bool(0x140003dfdf8?, {0x104f5c6f5, 0xb}, 0x1, {0x104fa23f3, 0x54})
	/opt/homebrew/Cellar/go/1.21.1/libexec/src/flag/flag.go:762 +0x70
flag.Bool(...)
	/opt/homebrew/Cellar/go/1.21.1/libexec/src/flag/flag.go:769
github.com/cloudprober/cloudprober/logger.init()
	/Users/test/git/github/cloudprober/logger/logger.go:44 +0x9c
```
thanks for looking into it.

**Comment by manugarg** [comment]
Hello @olegmayko 

Thanks a lot for filing this. It's the example extension code that needs to change. 

The new logger, actually introduced in [v0.12.9](https://github.com/cloudprober/cloudprober/releases/tag/v0.12.9), doesn't use glog anymore. To make sure that old invocations continue to work, we added a logtostderr flag to it, that does nothing.

I'll fix the example shortly. Essentially I'll drop the following line:
https://github.com/cloudprober/cloudprober/blob/aae829e83a29ab70b208033e3a4c3916cf4417e6/examples/extensions/myprober/myprober.go#L15

and use standard log here instead.

**Comment by manugarg** [comment]
Fixed example in https://github.com/cloudprober/cloudprober/pull/568

@olegmayko Can you please confirm that this was the only issue?

**Comment by olegmayko** [comment]
yes, i've changed the logger and it works. thank you. 
i will test further, as we have some other custom probes. I will close it later on.

**Comment by manugarg** [comment]
@olegmayko I am closing this one. Feel free to reopen if it's still an issue.
