### ISSUE TITLE
ping probe doesn't increment "total" metric if the target name can't be resolved

### ISSUE THREAD

**Issue by jinmeiib** [cloudprober/cloudprober#576]
**Describe the bug**

If the target of a ping probe is a domain name that can't be resolved, the probe reports the "total" metric that is not increasing. It's different from, e.g., tcp or http probes. It's not clear to me if this difference is intentional, but it would be better if the behavior in this case is consistent among different types of probes.

**Cloudprober Version**

0.13.0

**To Reproduce**

Run cloudprober with the following configuration. The target name `nosuchhost.jinmei.org` doesn't exist and can't be resolved.

```
probe {
  name: "HTTP probe"
  type: HTTP
  targets {
     host_names: "nosuchhost.jinmei.org"
  }
  http_probe {
    headers: [{
      name: "Host"
      value: "www.jinmei.org"
    }]
    method: GET
    protocol: HTTPS
  }
  interval_msec: 5000  # 5s
  timeout_msec: 1000   # 1s
  stats_export_interval_msec: 5000
}
probe {
  name: "TCP probe"
  type: TCP
  targets {
     host_names: "nosuchhost.jinmei.org"
  }
  tcp_probe {
    port: 80
  }
  interval_msec: 5000  # 5s
  timeout_msec: 1000   # 1s
  stats_export_interval_msec: 5000
}
probe {
  name: "PING probe"
  type: PING
  targets {
     host_names: "nosuchhost.jinmei.org"
  }
  interval_msec: 5000  # 5s
  timeout_msec: 1000   # 1s
  stats_export_interval_msec: 5000
}
```
Then the following logs will be emitted:
```
time=2023-10-18T14:20:48.346-07:00 level=WARN source=probes/tcp/tcp.go:178 msg="Target:nosuchhost.jinmei.org, doTCP: dial tcp: lookup nosuchhost.jinmei.org: no such host" system=cloudprober probe="TCP probe"
cloudprober 1697664045006931001 1697664048 labels=ptype=tcp,probe=TCP probe,dst=nosuchhost.jinmei.org total=1 success=0 latency=0.000
...
time=2023-10-18T14:20:46.678-07:00 level=WARN source=probes/http/http.go:290 msg="Get \"https://nosuchhost.jinmei.org\": dial tcp: lookup nosuchhost.jinmei.org: no such host" system=cloudprober probe="HTTP probe" target=nosuchhost.jinmei.org url=https://nosuchhost.jinmei.org
cloudprober 1697664045006931000 1697664046 labels=ptype=http,probe=HTTP probe,dst=nosuchhost.jinmei.org total=1 success=0 latency=0.000 timeouts=0 resp-code=map:code
...
time=2023-10-18T14:20:50.009-07:00 level=WARN source=probes/ping/ping.go:229 msg="Bad target: nosuchhost.jinmei.org. Err: lookup nosuchhost.jinmei.org: no such host" system=cloudprober probe="PING probe"
cloudprober 1697664045006931002 1697664050 labels=ptype=ping,probe=PING probe,dst=nosuchhost.jinmei.org total=0 success=0 latency=0.000 validation_failure=map:validator,data-integrity:0
```
As shown in the logs, all probes noted an error that the name can't be resolved. And the "total" metric for TCP and HTTP probes is incremented, but it's not for the PING probe.

**Additional context**

The direct reason why "total" isn't incremented in the ping probe is because [`ping.Probe.sendPackets`](https://github.com/cloudprober/cloudprober/blob/5d8755b9400e69adfbce02cf8a626a5332e8bb15/probes/ping/ping.go#L280) increments the `sent` counter only after sending the ICMP echo packet, and `Probe.Start` sets the "total" metric to the `sent` value. (I've not checked how TCP and HTTP probes handle this case).

**Comment by manugarg** [comment]
Not saying if it's correct or incorrect behavior but It has always been this way. Difference for the PING probes comes from the fact that for them we always resolve targets out of probe cycle, which was a deliberate decision to make sure DNS resolve time doesn't get counted as latency. In fact, you'll get the same behavior for the other probe types, if you add `resolve_first` to them.

**Comment by jinmeiib** [comment]
Thank you for the explanation. Please feel free to close this issue, then.

**Comment by manugarg** [comment]
@jinmeiib I am going to figure out if we can make it more explicit somehow -- like by default count resolve failures as errors. Or at least make it amply clear (I think logs should contain resolve failures anyway).

**Comment by manugarg** [comment]
#616 changed the resolve_first errors behavior for HTTP probe -we now increase the "total" counter regardless.

**Comment by manugarg** [comment]
#619 makes tcp probe consistent.
#620 makes ping probe consistent.

**Comment by manugarg** [comment]
I've decided to leave UDP as it is. The way it's implemented, it's not going to be easy.
