### ISSUE TITLE
Add ARM binaries and docker image

### ISSUE THREAD

**Issue by clarkezone** [cloudprober/cloudprober#58]
**Describe the feature you'd like and the problem it will solve**
Cloudprober doesn't current run out of the box on M1 macs or ARM based cloud hosting environments, it should.

**Comment by manugarg** [comment]
I didn't mean to close it yet.

**Comment by manugarg** [comment]
Multiarch images are available for the 'master' tag now:
[Docker hub: cloudprober/cloudprober:master](
https://hub.docker.com/layers/131728840/cloudprober/cloudprober/master/images/sha256-ebc0a2f5f63cf501935e50469efe2960843ddb246f7f158b9a9e2a071de7bc78?context=repo).

I'll enable them for release docker images ('latest', 'v..') after some time.

Pre-built binaries can be downloaded from the Github actions page for now:
https://github.com/cloudprober/cloudprober/actions/runs/1652292538

**Comment by manugarg** [comment]
Uploaded ARM binaries for the latest release v0.11.3.
https://github.com/cloudprober/cloudprober/releases/tag/v0.11.3

Also, updated the latest (also with tag v0.11.3) docker image:
https://hub.docker.com/layers/cloudprober/cloudprober/latest/images/sha256-6a3f217dc0f0d281f6d66c3fcc4a71b7de9e488fd1a2f234fac004a0af38d518?context=repo

**Comment by manugarg** [comment]
Verified today that the 'latest' image works on M1 Macs.
