### ISSUE TITLE
FIPS Compliance

### ISSUE THREAD

**Issue by sfc-gh-raram** [cloudprober/cloudprober#641]
**Describe the feature you'd like and the problem it will solve**
We want to use cloudprober in gov environments. To do so, we need cloudprober to be FIPS compliant. This leads to two questions.

1) Is cloudprober FIPS compliant?
2) If not, what needs to be done to make it FIPS compliant?

**Comment by manugarg** [comment]
@sfc-gh-raram Cloudprober doesn't manage any cryptographic keys. Also, it doesn't have any persistent storage of data (or sensitive data). I am not sure how FIPS apply in such a case. AFAICT, it is FIPS compliant, but please confirm with your security/legal team.

**Comment by sfc-gh-raram** [comment]
Thank you for your response, Manu. I'll follow up with the security team.
