### ISSUE TITLE
Probe timeout greater than probe interval should be allowed

### ISSUE THREAD

**Issue by Pulkit0110** [cloudprober/cloudprober#672]
Hi @manugarg, we noticed there was a change introduced a couple of months back where it is no longer allowed to have probe timeout greater than probe interval. We recently pulled those changes and now we have to use interval less than probe interval. But for our use case we want to trigger probes at every 10 seconds and have a timeout of 20 seconds as we want to do some operations like write, read, delete objects and then store these results which would take more than 10 seconds. 

As per my understanding, this change was introduced as there can be a possibility of duplicate probes(probe with same name) for timeout greater than interval. But can you let me know the exact reason for this change and also if there's something that can be done to accommodate our use case (or if it's possible to remove it or make it optional)?

**Comment by manugarg** [comment]
@Pulkit0110 Did you get a chance to look at my comment above?
