### ISSUE TITLE
Move cmd to cmd/cloudprober for simplified install

### ISSUE THREAD

**Issue by l2dy** [cloudprober/cloudprober#690]
**Describe the feature you'd like and the problem it will solve**

Currently the [Getting Started](https://cloudprober.org/docs/overview/getting-started/) guide gives 2 commands to install cloudprober and requires GOPATH, which is often not set in recent Go environments that uses Go modules.

```
go get github.com/cloudprober/cloudprober
GOBIN=$GOPATH/bin go install $GOPATH/src/github.com/cloudprober/cloudprober/cmd/cloudprober.go
```

I propose that we move `cmd` to `cmd/cloudprober`, so that the installation instructions can be simplified to

```
go install github.com/cloudprober/cloudprober/cmd/cloudprober@latest
```

and does not require the GOPATH environment variable anymore.

**Comment by manugarg** [comment]
Thanks @l2dy for reporting this. It makes sense but I'll need to change things in a bunch of places for this. I'll take a look at it.
