### ISSUE TITLE
"latest" tag outdated

### ISSUE THREAD

**Issue by haraldschioberg** [cloudprober/cloudprober#75]
**Describe the bug**
"latest" tag (0.11.3) is from before the migration to github.com/cloudprober . this means that 'go install' will fail.

Please add a new tag.

**Cloudprober Version**
0.11.3

**To Reproduce**
```
go install github.com/cloudprober/cloudprober@latest
go: github.com/cloudprober/cloudprober@latest: github.com/cloudprober/cloudprober@v0.11.3: parsing go.mod:
	module declares its path as: github.com/google/cloudprober
	        but was required as: github.com/cloudprober/cloudprober
```

**Comment by manugarg** [comment]
Ah, good catch. Thanks for filing this bug @haraldschioberg. I'll do that shortly.

**Comment by manugarg** [comment]
Done. Cut a new release v0.11.4.
