### ISSUE TITLE
Add resolved IP of http-probes' targets into a label

### ISSUE THREAD

**Issue by momoXD007** [cloudprober/cloudprober#77]
In short I am probosing to add a label that informs the user to which ip a hostname was resolved. This helps to debug unstable DNS-configs or problems related to DNS-load-balancing.

### Usecase:
Imagine you use DNS load balancing and than thanks to your cloudprober metrics you get a warning that something is wrong.
However, it just tells you https://example.net/awesome-api is down. However, that url resolves to different deployments depending on origin of the request and/or load-situation.  So, now you just know that at least one deployment is broken but not which one... This already helps but it would be even better to know to which deployment (in other words to which ip) the request that failed actually went.

### Details/additional notes:
In request.go line 112 that information is already present.  If my understanding of the source-code is correct the url_host variable contains the target's ip which was retrieved from dns.   It is however only internally available and at least I found no option to configure cloudprober to just save that data as a value to a label.
I would recommend to add an option to http-probes which allows this.
I furthermore want to add that enabling this feature might lead to a potentially huge amount of metrics in case the hostname tested resolves to a new ip on each request. From my experience this is very unlikely but I still want to point it out.

**Comment by manugarg** [comment]
Thanks for filing a detailed enhancement request, @momoXD007. I think it makes sense. I want to give it more thought though.

If we do it, I think it will make sense to do it through [additional labels](https://cloudprober.org/how-to/additional-labels/).

**Comment by manugarg** [comment]
Actually, now I remember that I had thought about some thing similar sometime back. 

The right way to do this will be to store IP address in the endpoint.Endpoint struct and update it when we resolve it. It will then be easy to add IP to labels. It will take multiple changes to do this cleanly. I'll update this issue with a plan.

**Comment by momoXD007** [comment]
making this feature optional sounds like a good plan to me! 
Thanks for considering my request :)

**Comment by manugarg** [comment]
Possible implemetation: https://github.com/cloudprober/cloudprober/pull/82.

**Comment by manugarg** [comment]
#82 has been merged. It will go out in the next release.

**Comment by manugarg** [comment]
Closing this now. Please see #82 for how IP label can be added to the metrics.
