### ISSUE TITLE
stackdriver surfacer is not capturing the streamed stdout or stderr

### ISSUE THREAD

**Issue by v-pratap** [cloudprober/cloudprober#817]
**Describe the bug**
Hi @manugarg 
In issue #691, the addition of stdout streaming seems to be functional. However, Stackdriver Surfacer doesn't appear to be consistently collecting these streamed metrics.
<img width="759" alt="Screenshot 2024-07-31 at 11 50 58 AM" src="https://github.com/user-attachments/assets/ac1d9090-8aab-488f-ab44-1b75bc352cca">
In this image, it appears we're attempting to emit 12 metrics over 60 seconds, but only 8 are visible. The 4 metrics seem to overwrite existing ones at the end of the interval.

<img width="705" alt="Screenshot 2024-07-31 at 11 54 58 AM" src="https://github.com/user-attachments/assets/943b153b-63a2-460f-b32b-acd07d1448cd">

This image is for stderr, we can see that messages are streamed(converted into multiple messages) but emitted at last.

**Cloudprober Version**
Latest

**To Reproduce**
This flag :  DisableStreamingOutputMetrics is false.

Stackdriver Config
```
surfacer {
  type: STACKDRIVER
  allow_metrics_with_name: "(request_count)"
  stackdriver_surfacer {
    metrics_prefix: 0
    metrics_buffer_size: 100000
    monitoring_url: "custom."
  }
}
```

**Additional Context**
It seems we are encountering this issue because we switched from a 25-second duration to a 60-second one. Previously, smooth streaming was achieved by adding the "emission_counter" metric label only to the final batch.

**Comment by manugarg** [comment]
Even though streaming output metrics is enabled (not disabled), I see metrics coming pretty close by -- there is a gap of about 12-13 sec. Stackdriver surfacer pushes metrics every 10s by default: https://github.com/cloudprober/cloudprober/blob/6320b294730c82d76ed7b2df70ac0cb66ea80aa7/surfacers/internal/stackdriver/proto/config.proto#L13

I think that's cutting too close. There are 3 ways to avoid this:

1. Add a rotating label to exported metrics, like this:
```
request_count{op=READ, status=SUCCESS, rotating_seq=1}
...
request_count{op=READ, status=SUCCESS, rotating_seq=10}
request_count{op=READ, status=SUCCESS, rotating_seq=1}
...
```
This way there won't be an explosion of timeseries and you won't overwrite anything. I think you can aggregate away rotating_seq while doing calculations.

2. Reduce stackdriver surfacer batch timer to something like 6s. I don't remember now how low you can go. Please check the stackdriver API quota docs.

3. Don't produce metrics this close. For more reliability leave a room of about 50%. So if batch timer is 10s, try to produce 15s apart.

I think 1st method is most reliable if that works for you. I'd also set batch timer as low as possible.

**Comment by v-pratap** [comment]
The emitted metrics are from our binary and it is configured to 12 seconds, even I did it 20 seconds the result remained same.
I have thought of 1st method but it would increase the cardinality of metric by huge margin and that's why I don't want to go through that method.

I  don't think batch_timer_sec has any role into this, every 12 seconds we are emitting metrics, and it is streamed out but it is not captured by stackdriver surfacer at any time.
What do you think?

**Comment by manugarg** [comment]
> I have thought of 1st method but it would increase the cardinality of metric by huge margin and that's why I don't want to go through that method.

How will it increase the cardinality of metric by huge margin? I see same metric repeated only twice every 60s. It wil increase cardinality only by 2 fold.

> I don't think batch_timer_sec has any role into this, every 12 seconds we are emitting metrics, and it is streamed out but it is not captured by stackdriver surfacer at any time.

Surfacer caught it and overwrote what it had. It needs to send old metrics first if you don't want it to be overwritten, which is what batch timer will do.

**Comment by v-pratap** [comment]
In this case I am emitting less metrics, but in our normal case we will emit metrics 4 times in 60 seconds, which means adding a 4 different metric label and in our system cardinality calculation is like (previous cardinality)* 4,  which is actually crossing the limit. Our cardinality limit is 5000 and currently we are at 1100.

`
Surfacer caught it and overwrote what it had. It needs to send old metrics first if you don't want it to be overwritten, which is what batch timer will do.
`
The default batch timer sec is 10 seconds and our metric emission is 12 seconds which I think should be fine but in the meantime it never picked these metrics. Stackdriver is emitting other metrics in every 10 seconds like cloudprober_version but it didn't emit our binary metrics like in this image:
<img width="470" alt="Screenshot 2024-07-31 at 6 53 06 PM" src="https://github.com/user-attachments/assets/07fa0a0d-27b0-4f21-a931-6836102f41fc">

**Comment by manugarg** [comment]
Interesting, `cloudprober_version` shouldn't even be generated every 10s, and I see that you've limited stackdriver surfacer to just request_count metrics. Where do you see stackdriver emitting `cloudprober_version` every 10s.

If stackdriver surfacer is sending 8 metrics instead of 12 every time, even when you're generating them 20s seconds apart, it seems like streaming is not working. Are you sure it's configured correctly? Asking because I am wondering how was it resolved last time?

To confirm if it's streaming or stackdriver surfacer, you can enable metrics logging by adding following stanza to probe config:

```
debug_options {
  log_metrics: true
}
```

**Comment by v-pratap** [comment]
Sorry, I forgot to mention that for cloudprober_version I have added `allow_metrics_with_name: "(request_count|version)"`. I will test the log_metrics options and get back to you.

`Asking because I am wondering how was it resolved last time?
`
Even I am not sure about it.

**Comment by v-pratap** [comment]
Looks like it is not getting streamed, all the metrics are logged at the last
<img width="1629" alt="Screenshot 2024-08-01 at 10 21 35 AM" src="https://github.com/user-attachments/assets/a4947eea-0c7c-4e19-a3a7-d3258f51cbf3">

The cloudprober configurations:

```
probe {
  name: ".."
  type: EXTERNAL
  targets { dummy_targets {} }
  external_probe {
    mode: ONCE
    command: "..."
    output_metrics_options {
      additional_labels: "..."
    }
  }
  debug_options {
    log_metrics: true
  }
  interval_msec: 60000
  timeout_msec:  60000
}

**Comment by manugarg** [comment]
I just tried to reproduce it locally, I couldn't:

```
#!/bin/sh

while true; do
	echo "a 12"
	sleep 2
done
```

config:
```
probe{
name: "test"
type: EXTERNAL
    targets { dummy_targets {} }
    external_probe {
      mode: ONCE
      command: "/tmp/x.sh"
    }
  interval_msec: 10000
  timeout_msec: 5000
}
```

logs:
```
cloudprober 1722564828477623090 1722564828 labels=ptype=external,probe=test,dst= a=12.000
cloudprober 1722564828477623091 1722564830 labels=ptype=external,probe=test,dst= a=12.000
cloudprober 1722564828477623092 1722564832 labels=ptype=external,probe=test,dst= a=12.000
```
3rd column is timestamp and you can see metrics coming in every 2s.

I think the only other suggestion I've is to verify the cloudprober version. It should be larger than v0.13.4. One way to do that will be to try adding `disable_streaming_output_metrics:  true` to external_probe section. On older versions that will fail.

**Comment by v-pratap** [comment]
I ma not sure how to verify the cloudprober version, But in our repository we keep cherry picking the features that we need, we do not pull all the changes from github and that might be the problem. But I have pulled all the changes related to streaming of stdout carefully.

With the below change:
<img width="557" alt="Screenshot 2024-08-02 at 11 37 03 AM" src="https://github.com/user-attachments/assets/424d2058-6703-4c04-b91b-dcf6d8eecddd">

I am getting these logs `disable_streaming_output_metrics: true`
<img width="720" alt="Screenshot 2024-08-02 at 11 37 41 AM" src="https://github.com/user-attachments/assets/2261408e-a564-4868-b873-6d0bfadea9d6">


and with `disable_streaming_output_metrics: false`
<img width="733" alt="Screenshot 2024-08-02 at 11 46 43 AM" src="https://github.com/user-attachments/assets/d0083547-5003-43ef-9555-4b12c259e2d8">


Here is the SetupStreaming function:
```
func (p *Probe) setupStreaming(c *exec.Cmd, target endpoint.Endpoint) error {
	stdout := make(chan string)
	stdoutR, err := c.StdoutPipe()
	if err != nil {
		return err
	}
	stderrR, err := c.StderrPipe()
	if err != nil {
		return err
	}
	go func() {
		defer close(stdout)
		defer stdoutR.Close()
		scanner := bufio.NewScanner(stdoutR)
		for scanner.Scan() {
			stdout <- scanner.Text()
		}
	}()
	go func() {
		defer stderrR.Close()
		scanner := bufio.NewScanner(stderrR)
		for scanner.Scan() {
			p.l.Warningf("Stderr: %s", scanner.Text())
		}
	}()

	go func() {
		for line := range stdout {
			for _, em := range p.payloadParser.PayloadMetrics(line, target.Name) {
				p.opts.RecordMetrics(target, em, p.dataChan, options.WithNoAlert())
			}
		}
	}()

	return nil
}
```

and runcmd_linux file is also same.

I will be looking into more depth, but if you suspect anything wrong please let me know. 

Thanks.

**Comment by manugarg** [comment]
@v-pratap I see. Can you also share a few lines that writing metrics to stdout and logging them? Is it Go code or something else? Other avenue to follow up will be if there is any buffering in your prober code at all..

**Comment by v-pratap** [comment]
In our code we are collecting all metrics from multi threaded structure and then emitting them. So the message you are seeing in cloud logger is from our binary.

C++ Code for final emission:
```
absl::Status MetricAggregator::EmitMetrics(bool add_unique_label) {
  for (const auto& [aggregator_function, metrics] : raw_metrics_) {
    absl::flat_hash_map<std::string, std::string> aggregated_metrics =
        aggregators_[aggregator_function]->Aggregate(metrics);

    for (const auto& [key, value] : aggregated_metrics) {
      std::string metric_name = key;
      std::string metric_value = value;
      if (add_unique_label) {
        AddUniqueLabelInMetric(metric_name);
      }
      std::cout << metric_name << " " << metric_value << "\n";
      cloud_logger_->Debug(absl::StrCat(metric_name, " ", metric_value));
    }
  }

  ++metric_emission_counter_;
  raw_metrics_.clear();
  return absl::OkStatus();
}
```

So from our code there will metrics emitted at 12 seconds and if probe end time is less than 12 seconds then it will emit early with unique metric label of emission_counter.

**Comment by manugarg** [comment]
>>      std::cout << metric_name << " " << metric_value << "\n";

Can you try changing this to:
```
std::cout << metric_name << " " << metric_value << std::endl;
```
That will force the output stream to flush.

Re: logs having correct timestamp, I think logger stores timestamps when you actually log it, so it ends up being correct in the logs viewer while logs are actually flushed asynchronously.

**Comment by manugarg** [comment]
I just tested this myself with the following program:
```
#include <iostream>
#include <chrono>
#include <thread>

int main() {
    while (true) {
        std::cout << "a 12" << "\n";
        // Second variation
        // std::cout << "a 12" << std::endl;

        // Sleep for 2 seconds
        std::this_thread::sleep_for(std::chrono::seconds(2));
    }
    return 0;
}
```

I don't get any output metrics with this variation (with "\n"), but I get correct metrics if I use `std::endl`.
```
std::cout << "a 12" << std::endl;
```

**Comment by v-pratap** [comment]
Thanks a lot @manugarg, I think it is working, I changed '/n' to std::endl
<img width="592" alt="Screenshot 2024-08-05 at 10 23 22 AM" src="https://github.com/user-attachments/assets/448f059c-aded-4207-a5a0-aa47bb20ba04">

**Comment by manugarg** [comment]
Well, that was interesting. C++ handles stdout differently than say Go, or Python. Glad using `stdl` worked out.
