### ISSUE TITLE
Support file path globs in config include

### ISSUE THREAD

**Issue by rhodesn** [cloudprober/cloudprober#826]
**Describe the feature you'd like and the problem it will solve**
It would be great if the new config `include: "xxx"` supported file path globs. It's fairly standard practice to have a drop-in style directory, e.g. `/etc/cloudprober/conf.d/*.cfg`, and maintaining a hardcoded list of files that live in this directory could quickly become cumbersome.

**Comment by manugarg** [comment]
It will go out in the next release, which is due next week.
