### ISSUE TITLE
Must add add_failure_metric:false on all surfacers to disable in Prometheus surfacer

### ISSUE THREAD

**Issue by rhodesn** [cloudprober/cloudprober#842]
**Describe the bug**
I want to disable failure metrics, which should be (afaict) this straight forward:
```
probe:  {
  name:  "test"
  type:  PING
  interval:  "2s"
  targets:  {
    host_names:  "www.google.com"
  }
  ip_version:  IPV4
}
surfacer {
  type: PROMETHEUS
  add_failure_metric: false
}
```

However Cloudprober always sets up a PROBESTATUS surfacer which defaults to `add_failure_metric: true`. Having a single surfacer with `add_failure_metric: true` causes the failure metric to be produced by the prometheus surfacer (maybe all surfacers that hold an copy of the metrics event?). Even disabling the PROBESTATUS surfacer doesn't work because the `surfaceWarpper.Write` is still called:
```
probe:  {
  name:  "test"
  type:  PING
  interval:  "2s"
  targets:  {
    host_names:  "www.google.com"
  }
  ip_version:  IPV4
}
surfacer {
  type: PROMETHEUS
  add_failure_metric: false
}
surfacer {
  type: PROBESTATUS
  probestatus_surfacer {
    disable: true
  }
}
```

The only way to get this working is to disable failure metrics on all surfacers:
```
probe:  {
  name:  "test"
  type:  PING
  interval:  "2s"
  targets:  {
    host_names:  "www.google.com"
  }
  ip_version:  IPV4
}
surfacer {
  type: PROMETHEUS
  add_failure_metric: false
}
surfacer {
  type: PROBESTATUS
  add_failure_metric: false
}
```

**Cloudprober Version**
0.13.7

**To Reproduce**
Run the first config and look for the `failure` metric.

**Additional context**
Adding a small sleep in this loop https://github.com/cloudprober/cloudprober/blob/master/prober/prober.go#L220 removes the issue, so guessing a race between that loop and a surfacer routine to process it's `emChan`?

Adding some "logging", the above loop triggered by a metrics event writes `em` to each surfacer containing `METRIC KEYS`, however by the time the prometheus surfacer runs the `ps.record()` function `em` now contains `failure`.
```
MetricsEvent
  Write.PROMETHEUS
    METRIC KEYS total
    METRIC KEYS success
    METRIC KEYS latency
    METRIC KEYS validation_failure
  Write.PROBESTATUS
    METRIC KEYS total
    METRIC KEYS success
    METRIC KEYS latency
    METRIC KEYS validation_failure
    METRIC KEYS failure
      ps.record() total
      ps.record() success
      ps.record() latency
      ps.record() validation_failure
      ps.record() failure
```

**Comment by manugarg** [comment]
@rhodesn Thanks for reporting this. There are a couple of ways to fix this and a workaround that will work now itself.

Workaround:
You can add the following to your surfacer config:
```
ignore_metrics_with_name: ^failure$
```

Possible fixes:
1. Clone EventMetrics before pushing them to surfacers. This is a more robust approach but more expensive for high frequency, busy cloudprober deployments.
2. Disable failure metric differently in surfacers.

I'll give it a little bit more thought and follow up with the fix.

**Comment by manugarg** [comment]
#844 will be a better fix overall, but suggestion in the previous comment should work as a workaround for now.
