### ISSUE TITLE
Improve OnGCE test and failure message

### ISSUE THREAD

**Issue by conallob** [cloudprober/cloudprober#868]
**Describe the bug**

When I attempt to run a test instance as per the getting started docs, I run into issues until I override the default values of the gcp_logging_endpoint flag.

**Cloudprober Version**

v0.13.7

**To Reproduce**

1. Attempt to run a cloudprober test instance on localhost as per https://cloudprober.org/docs/overview/getting-started/#configuration

```
cloudprober --config_file=/tmp/cloudprober.cfg 
time=... level=WARN source=logger/logger.go:302 msg="Error getting project id for google cloud logging: Get \"http://169.254.169.254/computeMetadata/v1/project/project-id\": dial tcp 169.254.169.254:80: connect: host is down, will skip" system=cloudprober component=global
```

After adjusting the CLI flags to this, the test instance is now running:

```
cloudprober --config_file=/tmp/cloudprober.cfg  --gcp_logging_endpoint="" 
```

**Additional context**

There appear to be two options:

* Update the default value of `--gcp_logging_endpoint` so that it is disabled by default

or

* Update the docs to undefine `--gcp_logging_endpoint`

**Comment by manugarg** [comment]
`--disable_cloud_logging` is a better flag. For some reason, cloudprober is detecting that you're running on GCE, i.e. [metadata.OnGCE()](https://pkg.go.dev/cloud.google.com/go/compute/metadata#OnGCE) is returning true.

Ideally I'd change the default but I want to avoid breaking things.

**Comment by manugarg** [comment]
There are two reasons for cloudprober to think you're running on GCE:

1. http://169.254.169.254 returns `Metadata-Flavor: Google`
2. `metadata.google.internal.` resolves to `169.254.169.254`

Can you please see if any of this is true.

Also, even if it thinks you're on GCE, but is not able to get metadata, cloudprober should only log a warning and keep on going:
https://github.com/cloudprober/cloudprober/blob/8e6bf4d6450a464d9c88d04a8aa778af2929a96e/logger/logger.go#L293
That seems like a reasonable compromise on systems that appear to be on GCE but don't have GCE metadata access.

@conallob can you please confirm?

**Comment by conallob** [comment]
```
% host metadata.google.internal     
metadata.google.internal has address 169.254.169.254

ping -c 1 metadata.google.internal
PING metadata.google.internal (169.254.169.254): 56 data bytes
1 packets transmitted, 0 packets received, 100.0% packet loss
```


I do have access to GCP projects, but I'm not trying to run a test instance on GCP, just on localhost

**Comment by manugarg** [comment]
I see, looks like your localhost may be running on GCP, or something else is emulating GCP metadata server on your network, because `metadata.google.internal` should ideally be accessible only from within GCP.

Regardless though, can you check if cloudprober keeps running with a warning message, even if you don't disable cloud logging explicitly through: `--disable_cloud_logging` and if that's sufficient to close this bug?

**Comment by conallob** [comment]
I suspect it's because I can use a VPN solution to get access to the GCP environments.


I'm afraid `--disable_cloud_logging` isn't enough, I get:

```
cloudprober --config_file=cloudprober.cfg --disable_cloud_logging
time=2024-10-01T11:51:24.032+01:00 level=ERROR+4 source=cmd/cloudprober/main.go:151 msg="Error initializing cloudprober. Err: sysvars_gce: error while getting project from metadata: Get \"http://169.254.169.254/computeMetadata/v1/project/project-id\": dial tcp 169.254.169.254:80: connect: host is down" system=cloudprober component=global
```

I think the problem is that you need to check if `metadata.google.internal` resolves **and** is reachable. In this scenario, it resolves in DNS, but is not reachable

**Comment by manugarg** [comment]
> I suspect it's because I can use a VPN solution to get access to the GCP environments.

I think accessing GCP environment is fine, it's just that resolving `metadata.google.internal` is expected to work ideally while running on GCP.

> ```
> cloudprober --config_file=cloudprober.cfg --disable_cloud_logging
> time=2024-10-01T11:51:24.032+01:00 level=ERROR+4 source=cmd/cloudprober/main.go:151 msg="Error initializing cloudprober. Err: sysvars_gce: error while getting project from metadata: Get \"http://169.254.169.254/computeMetadata/v1/project/project-id\": dial tcp 169.254.169.254:80: connect: host is down" system=cloudprober component=global
> ```
> 

That can be disabled using: `--cloud_metadata=none`.

> I think the problem is that you need to check if `metadata.google.internal` resolves **and** is reachable. In this scenario, it resolves in DNS, but is not reachable

yeah, metadata.OnGCE check is not perfect but that's the one provided by Google Go SDK. We can implement it ourselves but I wanted to avoid doing that as much as possible.

**Comment by manugarg** [comment]
@conallob Please see my previous comment: with appropriate flags, you should be able to run in your environment even if the current test (based on GCP's semi-official package) thinks you're on GCP. 

If yes, I'd like to repurpose this issue to be about improving the `OnGCE` test.

**Comment by manugarg** [comment]
Ack. Thanks.

I think it still makes sense to improve on this test. So, I'll keep it around and repurpose it.

**Comment by manugarg** [comment]
Thinking more about this, I think current tests are specific enough to Google, and overriding them will likely lead to more maintenance over time. Also, #892 will fix the awareness issue.
