### ISSUE TITLE
Improve Structured Logging For External Probes

### ISSUE THREAD

**Issue by sagepages** [cloudprober/cloudprober#893]
**Describe the feature you'd like and the problem it will solve**
Description of what you want to happen and what problem will it solve for you.

Currently with external probes, we see that logs do not keep the same structure when run with external probes. For example, they are emitted with a log `level=WARN` and the log messages are added under a `msg` field. This doesn't allow for great parsing and search-ability when passed to log storage services like Datadog logs or Opensearch. 

I wanted to formally request that log structure be maintained through external probes, perhaps behind a flag to enable this functionality. 

Happy to elaborate with examples or images or what I am referring to.

**Comment by manugarg** [comment]
What we can do here is to provide an option to not capture external probe process's stderr. That way external probe can log directly, retaining the log structure.

**Comment by manugarg** [comment]
@sagepages, I am wondering if just putting external process's log in a dedicated attribute might be enough:
```json
{"time":"2024-10-18T16:00:33.846-07:00","level":"WARN","msg":"process stderr","system":"cloudprober","probe":"test", "process_stderr":"{\"time\":\"2024-10-18T17:51:11.555769532-07:00\",\"env\":\"prod\", \"msg\":\"this is log\"}" "process_path":"/home/manugarg/x1"}
```

I think most log parsers can further parse individual fields. I asked ChatGPT if datadog can do it. It seems it can:
https://chatgpt.com/share/671304a1-9944-8005-9568-cdd058c1547c

Can you please verify.

Note that logs are currently not in the format I mentioned above. I've sent https://github.com/cloudprober/cloudprober/pull/899 for that.

**Comment by sagepages** [comment]
Yes, I think that having the log message be a separate field altogether is more than suitable. It can be filtered or parsed. Should be an ideal improvement.

**Comment by manugarg** [comment]
Closing this as #899 does what I proposed above.
