### ISSUE TITLE
GRPC Native Probes Cannot be Configured with a "port: XXXX" config option

### ISSUE THREAD

**Issue by conallob** [cloudprober/cloudprober#904]
**Describe the bug**
When configuring GRPC probes, the port config property cannot be set across multiple targets. It can only be set in host:ip string tuples.

**Cloudprober Version**

v0.13.7

**To Reproduce**

This config will result in cloudprober starting, but will fail to connect to the GRPC server successfully:

```
server {
  type: GRPC

  grpc_server {
    port: 3142
    enable_reflection: true
  }
}

probe {
  name: "grpc_generic"
  type: GRPC
  targets {
    # Hit another cloudprober instance running with grpc_server enabled.
    host_names: "localhost:3142"
  }

  grpc_probe {
    method: GENERIC
      request {
        call_service_method: "cloudprober.Cloudprober.ListProbes"
        body: "{}"
      }
    }
}
```

However, this config will result in cloudprober refusing to start, because the grpc_probe data structure does not support specifying a port for all targets.

```
server {
  type: GRPC

  grpc_server {
    port: 3142
    enable_reflection: true
  }
}

probe {
  name: "grpc_generic"
  type: GRPC
  targets {
    # Hit another cloudprober instance running with grpc_server enabled.
    host_names: "localhost"
    port: 3142
  }

  grpc_probe {
    method: GENERIC
      request {
        call_service_method: "cloudprober.Cloudprober.ListProbes"
        body: "{}"
      }
    }
}
```

The error log is:

```
time=[REDACTED] level=ERROR+4 source=cmd/cloudprober/main.go:151 msg="Error initializing cloudprober. Err: error processing config. Err: proto:\u00a0(line 16:5): unknown field: port" system=cloudprober component=global
```

**Additional context**

My ultimate goal is to be able to use a single file target to specify multiple hosts, complete with additional label information. Destination ports are excluded from the file target, allowing each probeset to configure their own destination port, or defer to the default of that probe type.

**Comment by manugarg** [comment]
> ```
>   targets {
>     # Hit another cloudprober instance running with grpc_server enabled.
>     host_names: "localhost"
>     port: 3142
>   }
> ```

This config is wrong because `targets` message doesn't take a port.

First config will work if you either enable TLS on the server or use `insecure_transport: true` in gRPC probe config.

**Comment by conallob** [comment]
Reframing my question in the language of https://cloudprober.org/docs/how-to/targets/#probe-configuration-through-target-fields --

Why is GRPC not considered a port aware probe (which can be configured with a port field) when I can specify the port both in host:ip formatted targets and the server port? Could it be considered a port aware probe please?

**Comment by manugarg** [comment]
gRPC is actually port aware, i.e. it uses target's port. What you're asking for is an option to set port at the probe level. That's doable.

**Comment by manugarg** [comment]
Done through #905.
