### ISSUE TITLE
HTTP probes don't refresh bearer tokens

### ISSUE THREAD

**Issue by jtse** [cloudprober/cloudprober#93]
**Describe the bug**
My probes against a Google API were initially succeeding but failed with a 401 after an hour. Upon further debugging, I realized:

*  The [HTTP request is created once](https://github.com/cloudprober/cloudprober/blob/master/probes/http/http.go#L443) and used _repeatedly_ for each probe request.
*  The bearer token header is set at the time of HTTP request creation.
*  So in effect, the same bearer token is used over and over. If it bearer token is short-lived like an access token, then the probe will fail when the token expires.

Practically speaking, cloudprober can't be used against many web APIs until this bug is fixed.

Note that cloudprober _is_ getting new access tokens but just isn't using them in the HTTP request. I was able to fix this by simply creating a new HTTP request instance for each probe request.

**Cloudprober Version**
0.11.4 but I suspect it affects the past few versions.

**To Reproduce**
1. Decide on a Google API to test.
2. Open Google Cloud's Cloud Shell (shouldn't cost any).
3. git clone and compile cloudprober.
4. Create a cloudprober.cfg similar to the following:
```
probe {
  name: "foo"
  type: HTTP
  targets {
    host_names: "foo.googleapis.com"
  }
  http_probe {
    relative_url: "/path/to/api/endpoint
    protocol: HTTPS
    method: POST
    headers {
      name: "content-type"
      value: "application/json"
    }
    // Will auth with the Cloud Shell user's access creds.
    oauth_config {
      google_credentials {
      }
    }
  }
  interval_msec: 30000
  timeout_msec: 1000
  validator {
    name: "status_code_200"
    http_validator {
      success_status_codes: "200"
    }
  }
}
```
5. Run cloudprober in Cloud Shell.

Expected: 200
Actual: 200 and then 401s when the token expires.

**Comment by manugarg** [comment]
Thanks for the bug report @jtse. I'll take a look at it.

**Comment by manugarg** [comment]
I see, so we periodically get the new token here:
https://github.com/cloudprober/cloudprober/blob/1dfdd012c8efbad0695b717498ad8f46f9021055/probes/http/http.go#L595

But we recreate HTTP request only if we're resolving first (i.e. `resolve_first` is enabled):
https://github.com/cloudprober/cloudprober/blob/1dfdd012c8efbad0695b717498ad8f46f9021055/probes/http/http.go#L466

So one workaround for this will be to simply add resolve_first to your http_probe {} stanza. I'll submit a fix for this soon.

**Comment by jtse** [comment]
Wow that was quick!  Thanks!

Yeah I tried the `resolve_first` but rather into some other resolution-related error, but didn't dig further.

**Comment by manugarg** [comment]
Possible fix: https://github.com/cloudprober/cloudprober/pull/94

**Comment by manugarg** [comment]
Merged the fix. This will go out in next release, mostly in a couple of weeks. You can use the "master" docker tag, or see https://github.com/cloudprober/cloudprober/wiki/Download-unreleased-binaries for how to use unreleased binaries in the meantime.

Once again thanks for reporting this bug @jtse.

**Comment by jtse** [comment]
Thank you so much for the quick fix. I verified this is working w/ the latest Docker image.

**Comment by manugarg** [comment]
Great. Thanks a lot for verifying!
